### ISSUE TITLE
Improve footnotes

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#1007]
At this moment footnotes are put at the end of each chapter, that gets ugly when generating a PDF. We have two options here:
- show them at the foot of the page where they are called, like real footnotes
- show them at the end of the chapter but on its own page

This way it gets cleaner and a better separation of the footnotes from the main text.

**Comment by jpmarindiaz** [comment]
+1

**Comment by ljgww** [comment]
Since PDF format has limited vertical size perhaps second solution is better. 

It also depends on size of the footnote. Sometimes it will be hard to determine how to render footnotes like in printed books, for example: footnotes takes half of the page but if one put reference in the text on the page, reference may flow to the next page (as to accomodate space for footnote), and if reference goes to the next page footnote will follow leaving empty space for the text (with reference) on original page. Seen in some books that footnote will also flow to the next page (effectively making a footnote on the page that do not have reference)
