### ISSUE TITLE
Multi-Language UI

### ISSUE THREAD

**Issue by jamiebuilds** [GitbookIO/gitbook#1080]
I'm currently setting up translations for the Redux project: http://redux.js.org / https://github.com/rackt/redux/pull/1198

My concern right now is that for multiple language support GitBook decides to replace your homepage and doesn't provide a good way for changing between languages.

The homepage being just a list of languages is a huge problem for losing the existing search engine rankings. There's also the issue that if someone is linked to a particular page they have no way of even knowing that they can change the language.

It would be awesome if the homepage defaulted to one of the languages' READMEs or even a custom markdown file. Then have a dropdown in the primary toolbar where you can select the language at any time (the dropdown taking you to the same page in a different language or the language's homepage if it does not exist).

**Comment by nagim** [comment]
Hi,

Did you have a look at the [versions](https://plugins.gitbook.com/plugin/versions) plugin?
Maybe it helps.

**Comment by erlend-sh** [comment]
I'm glad I found out about this before I started the transition to multi-lingual. The lack of a handy language selector is indeed a big drawback. I'm also missing a good live example of a multilingual site, since the [Learn Git](https://github.com/GitbookIO/git) book is no longer live.

**Comment by erlend-sh** [comment]
So I just went through the process of setting up a multilingual GitBook, and I’d like to provide some constructive criticism on that experience. 

**Moving the main language into a language folder seems weird**

It feels awkward to me, having to move my main content (in my case my English content) into its own sub-folder, in terms of file hierarchy as well as URL, in order to accommodate multilingual functionality. That’s my *main content*. It’s different from the rest. Every original article will start in that language. I think it’s okay to treat it a bit differently.

And as a user you're currently forced into the awkward decision of (a) putting all your content into a `/en/` folder now even though it's the only language or (b) add it in later and cause URL breakage.

**Why do I have to create a summary file for *all* languages?**

Maybe more importantly, it feels super awkward to maintain two or more SUMMARY.md’s. My main language should dictate the SUMMARY.md, else you risk alternative languages diverging from the intended order & hierarchy of your content.

### Suggesting a slightly different language setup

1. I enable multilanguage via the plugin.

2. There’s now a new option available to me when I right click the root of the Table of Contents box. 
<img width="311" alt="multilang1" src="https://cloud.githubusercontent.com/assets/583842/13547202/82df6b36-e2c8-11e5-837e-4993e6b925f3.png">
Clicking the "New Language" button will not open a freeform text box, it’ll open a language selector. You pick the language you want to add.

3. Then the folder gets added. And inside that folder are empty copies of all the main files in your book (like when you’ve added a new .md file but you haven’t started editing it yet, so it exists on GitHub but it doesn’t exist in the book.)
<img width="193" alt="screen shot 2016-03-05 at 11 44 37" src="https://cloud.githubusercontent.com/assets/583842/13547189/c1ca433a-e2c7-11e5-9f4f-a3e05ee76d59.png">

4. Filling in one of these .md files will add that file to the same, universal SUMMARY.md, but under its own language-specific list.

5. Whenever new files are added in the main language, other languages are automatically updated with empty files.

**Comment by PauloASilva** [comment]
Anything new about how Gitbook Multi-Languages works?

**Comment by rokde** [comment]
It does not work anymore. :(
I tried anything documented, nothing works. We removed the multi-lingual stuff and added the language-tocs to the root summary.md file.

**Comment by CleverCat123** [comment]
@erlend-sh  Hi sir what is the name of that plugin Thanks very much 
                           you said: multilanguage via the plugin

**Comment by erlend-sh** [comment]
I do not recall, but I'm guessing it was one of these: https://plugins.gitbook.com/browse?q=language

**Comment by CleverCat123** [comment]
@erlend-sh  thanks for your reply and have a nice day
