### ISSUE TITLE
When using anchor for section in Summary, it won't scoll to the right position (v3.0.0.pre.1)

### ISSUE THREAD

**Issue by jinzhu** [GitbookIO/gitbook#1163]
![screenshot](https://cloud.githubusercontent.com/assets/6843/13354823/55482e56-dcd8-11e5-8df3-eb8af0a6d1f5.png)

Online DEMO: http://jinzhu.me/gorm/models.html#conventions-overriding-conventions

Also should we change menu's highlight when scroll to the next menu? I think this will happened often when using anchor in summary.

**Comment by nagim** [comment]
Hi,

Out of curiosity, I checked your book, and all the other anchored summary elements are working fine, except that one. So the problem is with the anchor text in the summary.
According to your source files, double dash should be used for that anchor.

The correct summary entry would look like this:

```markdown
  * [Naming Conventions & Overriding](models.md#conventions--overriding-conventions)
```

Hope that helps!

Cheers,
Imre

**Comment by jinzhu** [comment]
Hi @nagim 

As I am using this plugin `anker-enable`, so it works now. By default, it doesn't.

**Comment by nagim** [comment]
Hi,

Yes, I tried also and I can confirm, not working by default.
