### ISSUE TITLE
Start writing a Gitbook -> Modify authorization

### ISSUE THREAD

**Issue by SerkanSipahi** [GitbookIO/gitbook#1164]
I want to write my documentation over Gitbook but someting (see below message from Gitbook) makes me confused :(

- Message from Gitbook
Modify authorization
GitBook by @GitbookIO would like to modify its permission to access your account

+ Added permissions
Repository webhooks and services
Admin access
This application will have full access to repository webhooks and services (no direct code access).

My Question: What does mean: "Admin access with full acces to repository" (see above) ! It that secure for me?

**Comment by SamyPesse** [comment]
Sorry for the late response.

First of all, you can login on GitBook using GitHub without granting all of these authorizations, we have multiple level of authorization requests for GitHub users:
- **Login only**: we only have access to the basic info and email
- **Access to public repositories**: we can list public repositories, edit them and admin them (for adding a webhook)
- **Access to private repositories**: we can list public & private repositories, edit them and admin them (for adding a webhook)

So, why do we need `Admin access with full acces to repository`?

When you select a GitHub repository to create a GitBook, we import the book, then we add a webhook to it. The webhook allows GitBook.com to be notified everytime you commit to your GitHub repository, so that we can update the GitBook accordingly.

Adding a webhook is only possible using the `admin:repo_hook` scope from the [GitHub API](https://developer.github.com/v3/oauth/#scopes).

GitBook.com is requesting this list of scopes from GitHub: `user:email, read:org, repo, admin:repo_hook`.

So Is that secure for you? This is a relation of trust, but you can [revoke](https://github.com/settings/applications) at any time the access you granted, or access an [audit logs](https://github.com/settings/security) of the actions we do on your behalf.
