### ISSUE TITLE
Modify content based upon build type

### ISSUE THREAD

**Issue by blittle** [GitbookIO/gitbook#120]
It would be nice to modify content based upon the destination output. For example, in the web version of my book I would prefer to have animated gifs for images to show more complete examples whereas in a PDF version, I would rather have a different image. I might be able to hack something together, but it would be nice to have some standard way to define content for different types of output.

**Comment by SamyPesse** [comment]
This is now possible in version 2.0.0 using:

```
{% if gitbook.generator == "ebook" %}
For PDF, ePub, Mobi
{% else %}
For website
{% endif %}
```

**Comment by cwm83** [comment]
In case anyone else is trying to do this: I'm not sure if it is due to a change in version 2.1.0, or if I am doing something wrong, but to get content specific to pdf,  I had to use 
`{% if gitbook.generator == "pdf" %}`

Using `gitbook.generator == "ebook"` returned false, and went to the website content
