### ISSUE TITLE
Error loading your book

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/gitbook#1236]
Hello guys 

I'm getting the following error when I open a book

```
An unexpected error occurred when trying to load your book: References 'refs/remotes/origin/master' not found
```

OS: Ubuntu 15.10 64-bit
Gitbook Editor: 5.0.5

**Comment by nagim** [comment]
Hi,

This usually comes up for me when I have the repo opened in another editor (like Atom).

Cheers,
Imre

**Comment by KINGSABRI** [comment]
@nagim thanks

Actually, I didn't, until this error appeared, then I open it with Kwrite/Kate 

Any fix for that, plz?

**Comment by Abel-Torres** [comment]
Same error for me. It was working one day then the next day, without having changed anything, I opened Gitbook Editor and got this error. While looking around on web I found that the Gitbook errors.html file doesn't exist. That yields a 404 error. In general, I find that user documentation is really lacking and seems that nobody is responding to these comments either.

**Comment by SamyPesse** [comment]
@KINGSABRI @Abel-Torres Sorry for the late response. A few questions to help me debug the issue:

- Does the Git repository associated to your book still has the remote `origin`? You can paste me the output of `git remote show origin` in the book's folder.
- What is the output of `git branch` ?

@Abel-Torres Since a few weeks, we are working on improving our documentation, both for GitBook.com and the GitBook toolchain.

The documentation for the GitBook Toolchain lives at [toolchain.gitbook.com](http://toolchain.gitbook.com), and its source at [GitbookIO/gitbook/tree/master/docs](https://github.com/GitbookIO/gitbook/tree/master/docs)
The new documentation for GitBook.com lives at  [help.gitbook.com](http://help.gitbook.com), and its source at [GitbookIO/help.gitbook.com](https://github.com/GitbookIO/help.gitbook.com).

Feel free to collaborate on both (issues or PRs are welcome).

There are still a few dead links that we are working on fixing.

**Comment by NDuma** [comment]
> #### Error loading your book:
> An unexpected error occurred when trying to load your book: Branch "undefined" doesn't exist

I changed the name of the book in the settings & linked it to GitHub; now it won't load.

**Comment by nuprin** [comment]
Running into this issue as well.

It's very discouraging after having invested several hours in creating the content.

**Comment by nuprin** [comment]
Resolved by unlinking from the Github repository I was trying to sync to.

Here was the error message, if helpful:

![github_-_tech_lead_training_ _gitbook](https://cloud.githubusercontent.com/assets/155143/18457355/f66ce2ec-790c-11e6-9792-31f667ef10b8.png)

**Comment by leondu** [comment]
Same here, you have to unlink from Github repo, this is really strange.

**Comment by pboyer** [comment]
This occurred for me when I tried to link to a Github repo that I had not yet added any content to. 

To repro:

1. Create github repo. Add no content.
2. Create gitbook book
3. Link gitbook with Github repo
4. Attempt to edit through Gitbook interface

**Comment by Passluo** [comment]
the same to me

**Comment by thedaviddias** [comment]
I have the same issue... Any update?
