### ISSUE TITLE
pdf output

### ISSUE THREAD

**Issue by lisaluescher** [GitbookIO/gitbook#1240]
Hi,

I'd like to build my gitbook with the output of a *.pdf file. If I run "gitbook help" I see the command "gitbook pdf" to get a pdf output. But I get an error message if I do so.
I saw some issues about the pdf output but they where for Mac OS or Linux. I'm using Windows 7.

How can I get a pdf of my gitbook without using gitbook.com?

Thanks for your answer.

**Comment by Tiliavir** [comment]
You have to install Calibre and add it to the PATH variable first.
Then execute "gitbook pdf"

**Comment by lisaluescher** [comment]
I'm not sure if I understood it right. Should I put something like this in my book.json:
{
    "variables": {
        "PATH": "C:\Program Files (x86)\Calibre2\calibre.exe"
    }
}
Because I get the exact same error message

**Comment by Tiliavir** [comment]
First make sure, youve restarted the prompt after installing Calibre. Then verify "ebook-convert" is available in the command prompt by running `ebook-convert --version`. If so, `gitbook pdf` should work.. otherwise follow this guide, to make ebook-convert available from the command line:
http://www.computerhope.com/issues/ch000549.htm

The path you have to add should be the installation path of Calibre. And therefore similar to this:
"C:\Program Files\Calibre2"

**Comment by lisaluescher** [comment]
It worked. I just hadn't installed ebook-convert properly because I installed it before I installed calibre.
Thank you so much!
