### ISSUE TITLE
Importing Gitbook Modifies Global Prototypes

### ISSUE THREAD

**Issue by steve-gray** [GitbookIO/gitbook#1283]
Hey,

I have a gulpfile that has a few tasks:
- Docs (Generate docs with esdoc)
- Books (Generate gitbook for manual with 'website' mode)

The issue is that if the books task manages to run before the docs task, various global prototypes and objects are modified that cause some objects to become recursive. It looks like something somewhere is relying on transpiled ruby (the chain of references starts off with some odd looking OpalClass types).

I know that 'being a good module' is on the todo items, but I was wondering if this issue can be addressed somehow by a flag or option that prevents the Opal'd code modifying global prototypes? Also, is it Gitbook directly or an upstream dependency that's guilty of this?

-Steve

**Comment by SamyPesse** [comment]
I agree that this is not perfect when using GitBook as a library.

GitBook is using [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js) which is using Opal; so GitBook is not directly guilty of this.

I don't have a clean solution in mind right now.

**Comment by hrhino** [comment]
This is making life pretty hard for me (since I'm running gitbook to generate documentation pages inside of webpack). Obviously it's not your fault, though.

I don't know how difficult this would be, but what about publishing a `gitbook-markdown-only` package that drops asciidoc support? That would still be suboptimal for people using asciidoc but it would at least enable some use cases.

Just an idea; I'm going to do the exact same thing in my company's local registry to get this working. Thanks!
