### ISSUE TITLE
File 'Save' is erratic

### ISSUE THREAD

**Issue by Abel-Torres** [GitbookIO/gitbook#1295]
There is no consistent behavior in the Save function.

**Comment by SamyPesse** [comment]
Can you detailed a little more the issue?

We are working on a serie of improvements for the editor that improve the reliability.

**Comment by Abel-Torres** [comment]
I am using Gitbook Editor on my local machine. I have all files on my disk.

When I modified a file with the editor, then use the Save option, I do not see that the file has been saved. Namely, the timestamp is unchanged; the content of the local file does NOT contain the changes I made in the editor. 

The Save function is opaque and unreliable. Apparently Gitbook is saving my local files somewhere without my knowing it. Those files may or may not overwrite the local file.

**Comment by Wideshanks** [comment]
It seems as if the Gitbook editor sometimes doesn't persist the changes to disk. Closing the editor seems to persist them to disk.

**Comment by voidmain** [comment]
I have this same issue. Additionally, the GitBook editor can't push to my corporate git repository because it uses SSH, so I can't really figure out a way to use the editor for local editing.

The odd thing is that if I close GitBook editor and then re-open it, the changes I made are still there. However, they are not in the file if I open it using `vi` on the command line. @Wideshanks seems to have a different experience with closing the editor. That solution doesn't work for me at all.

I've done some searching on my file system to see if I can find where GitBook is storing the files and I couldn't figure it out. There was nothing in the `~/GitBook/` directory. There also wasn't anything in the `~/Library/` directory either.

Seems like a lot of magic for something that should be very simple. If you edit a file and hit save, it should write the changes to disk. Not sure why you guys aren't doing this and instead storing changes in some magic location that doesn't align with where the files are on disk.

**Comment by Wideshanks** [comment]
> @Wideshanks seems to have a different experience with closing the editor. That solution doesn't work for me at all.

No, I was wrong. It's not saving them when I close. Must have been a fluke.
