### ISSUE TITLE
Feature Request: add support MultiMarkDown

### ISSUE THREAD

**Issue by sdebnath** [GitbookIO/gitbook#131]
MultiMarkDown supported by apps like ByWord and Scrivener has a ton of features that are very useful for writing longer articles or books. Would be a perfect addition to GitBook.

See [MultiMarkDown Documentation](https://github.com/fletcher/MultiMarkdown/blob/master/Documentation/MultiMarkdown%20User%27s%20Guide.md)

**Comment by chriseana** [comment]
Great Idea! I, mean, necessary. ;)

**Comment by kmelve** [comment]
I second this. Although many of the features in MMD is already supported (tables and so on), MMD is one of the most well kept and comprehensive flavours out there. That being said, which markdown flavours to support could easily turn into a rabbit hole.

**Comment by SamyPesse** [comment]
With GitBook 2.0.0, a MultiMarkdown parser could be really easy to write, using the same base as https://github.com/GitbookIO/gitbook-asciidoc

We can just change the parsing to html method here: https://github.com/GitbookIO/gitbook-asciidoc/blob/master/lib/utils/convert.js#L14 and use https://www.npmjs.com/package/multimarkdown

But I don't think it's a good idea to support it yet, because it'll not be correctly supported in the editor (https://www.npmjs.com/package/multimarkdown can't be used in the browser), and kramed is already supporting most of the syntax.

**Comment by agmarrugo** [comment]
I think that using MMD is a great way for supporting citations which [many people have been asking for a while.](https://github.com/GitbookIO/gitbook/issues/134)

**Comment by newhobby2016** [comment]
cross reference and citation are essential for academic writing, which is missing in the kramed.

**Comment by johanneskoester** [comment]
Dear devs, any update on this? Academics is eagerly waiting for this!

**Comment by johanneskoester** [comment]
I am happy to help if that is possible.
