### ISSUE TITLE
Commit ... doesn't exist in repo

### ISSUE THREAD

**Issue by pcha** [GitbookIO/gitbook#1313]
We made some changes in github, but they wasn't pushed to gitbook. I watched in the github webhook and shows several failled pushes. Their responses are like this:
`{"ok":false,"event":"push","error":"Commit c077cc5aae7992159fefd834562b26125fd7847b doesn't exist in repo"}`

**Comment by AaronO** [comment]
I assume you're using a private GitHub repo ?

@pcha This is caused by a really annoying issue with GitHub, that makes it "impossible" to authenticate a user over oAuth without erasing his scopes (or requiring them to confirm each time). This happens when you logout then login with GitHub.

Basically GitBook doesn't have the permissions to pull your GitHub repo (because those permissions have been cleared).

Simply go to your GitBook's user's settings (the one who owns the webhook) and in the GitHub section reauth with GitHub to grant permissions to private repos (see dropdown).

**Comment by pcha** [comment]
Ok, thank you very much. I did it and works.
Then, if I understood,I need to log in me with gitbook instead of github to avoid than this issue will occur again. Is it true?

**Comment by AaronO** [comment]
Yes in the meantime, you can set a password in your account's settings.

This is a really frustrating issue, but we'll add warnings for when the git server detects a webhook but invalid auth and we'll reach out to the folks at GitHub so they can fix and implement a more sane behavior. (Other users of GitHub's oAuth/api have the same frustration).

Happy you got it working !

**Comment by pcha** [comment]
Ok, thank you very much again!!
