### ISSUE TITLE
What context / variables are available to themes?

### ISSUE THREAD

**Issue by Simran-B** [GitbookIO/gitbook#1367]
I modified a fork of `theme-default` to include something custom:

```
{% include "website/navigation.html" %}
```

In that file, I want to link to another Gitbook, which is stored adjacent to the current Gitbook, e.g.

```
http://docs.contoso.com/BookOne/   -- link to \
http://docs.contoso.com/BookTwo/   <----------/
```

No matter what sub-page I'm on, e.g. `BookOne/foo/bar/index.html`, the link is supposed to point to BookTwo. My first idea was to write a plugin, that dynamically creates the link using `gitbook.state.bookRoot` (what's the difference to `gitbook.state.root` BTW.?). But I wonder if the same could be achieved in the template itself, somehow like this:

```
<a href="{{ book.root }}/../BookTwo">AQL</a>
```

The logic is: take the `book.root`. go one folder up and go to `BookTwo` (adjacent to `BookOne`). The resulting link would ideally not contain `HOST/BookOne/../BookTwo`, but only `HOST/BookTwo`.

Is there a way to do this and have the path resolved properly, when running offline as well as online with AJAX?

And in general, I wonder if there's any documentation about what is available in Gitbook's templating language.

**Comment by SamyPesse** [comment]
### Extend, instead of forking

First of all, If your theme will be similar to the default one, don't fork it, you can extend it instead:

For example, if you have a `theme-mycustom` plugin, it will be loaded before the default theme, and you can extend the page template by creating a `_layouts/website/page.html`:

```html
{% extends template.self %}

{% block book_navigation %}
{% endblock %}
```

Here is a complete example: [theme-api](https://github.com/GitbookIO/theme-api).

### Variables

Themes have access to all variables of templating: http://toolchain.gitbook.com/templating/variables.html

### Difference between `gitbook.state.bookRoot` and `gitbook.state.root`

One is the root relative to the language book (for multilingual book), the other is absolute root for the whole book.

**Comment by SamyPesse** [comment]
To answer your use case: we can probably expose `path` module as filter to join urls (we can also already look at the default filters: https://mozilla.github.io/nunjucks/templating.html#builtin-filters).

**Comment by Simran-B** [comment]
**Extending:** I couldn't wrap my head around how this works yet, but maybe forking is the only options anyway... I believe this would be the correct place to insert / include my html into the page:

![image](https://cloud.githubusercontent.com/assets/7819991/15905136/0640014e-2db4-11e6-8ac8-55ce30addd65.png)

If I did the following, would that include my html *before* `<div class="book">`?

```
{% block body %}
  {% include "website/navigation.html" %}
  {{ super() }}
{% blockend %}
```

**Variables:** Thanks! Will they update though if served by a web server? I ran into an issue in 2.x when I let a script write the correct relative paths into the pages - it worked with offline files, but as soon as they were served through a web server, I ran into invalid links (I assume because AJAX only fetched the new content, but did not replace the header of the target page).

**roots**: Good to know!
