### ISSUE TITLE
<property name="" value=""/> in markdown  appear errors after building

### ISSUE THREAD

**Issue by taotao365s** [GitbookIO/gitbook#1407]
> gitbook build ./book

info: loading book configuration....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 
info: >> 4 plugins loaded 
info: start generation with website generator 
info: clean website generator
info: OK 

Template render error: (/Users/xxx.md)
  SyntaxError: Unexpected token ILLEGAL (In file 'xx.md')

**Comment by SamyPesse** [comment]
I don't understand the issue. Please provides more details.

**Comment by chaserjs** [comment]
Hi, I ran into the same error message after I copied/pasted some text from Word into the gitbook editor.

It turned out to be caused by some weird invisible unicode character (I guess) that got mixed into the text, for example:
```
$ cat login.txt
login:  
password:

$ od -c login.txt
0000000   l   o   g   i   n   :     342 200 250  \n   p   a   s   s   w
0000020   o   r   d   :  \n  \n
0000026
```

Now I understand, character like this is technically illegal and should be cleaned up. I feel the actual problem is the error message from gitbook build process is too generic:

```
Downloading source
Pulling from S3
Extracting source
GitBook version is 3.2.3
Tweaking book.json
Installing plugins
info: installing 1 plugins using npm@3.9.2 
info:  
info: installing plugin "comment" 
info: install plugin "comment" (*) from NPM with version 1.0.5 
/tmp/book
└── gitbook-plugin-comment@1.0.5 

info: >> plugin "comment" installed with success 
Building Site, will upload
info: 8 plugins are installed 
info: 7 explicitly listed 
info: loading plugin "comment"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 2 pages 
info: found 1 asset files 
error: error while generating page "chapter1.md": 

Template render error: (/tmp/book/chapter1.md)
  SyntaxError: Unexpected token ILLEGAL
```

This error can easily happen when copying text from other WYSIWYG editors like Word.

For better writer's experience I would recommend the following improvements in gitbook compiler/publish process: 
when detecting illegal token in the md file, please report additional information e.g.
- line number and position where the illegal token was found
- characters of the illegal token, in case the characters are invisible hex values of the characters

Thank you!
