### ISSUE TITLE
Weird footnotes

### ISSUE THREAD

**Issue by belen-albeza** [GitbookIO/gitbook#1458]
This markdown syntax for footnotes:

```
Blah blah[^foo].

[^foo]: Lorem ipsum
```

Produces the following HTML. No auto-numbering, and they appear in a `blockquote` (probably not the right choice semantically) right after the citation, instead of at the end of the document/section.

---

<img width="414" alt="screen shot 2016-07-21 at 10 50 25" src="https://cloud.githubusercontent.com/assets/63681/17016818/18200302-4f31-11e6-871f-0e3cb879a1de.png">

**Comment by belen-albeza** [comment]
I made some tests, it is an issue from [markup-it](https://github.com/GitbookIO/markup-it).

With this node script:

```
let text = `Bla bla *blah*[^waka].

[^waka]: Lorem ipsum waka waka eh eh~

Some more text in here.`;

console.log(html.toText(markdown.toContent(text)));
```

It renders:

```
<p>Bla bla <em>blah</em><sup><a href="#fn_waka" id="reffn_waka">waka</a></sup>.</p><blockquote id="fn_waka">
<sup>waka</sup>. Lorem ipsum waka waka eh eh~<a href="#reffn_waka" title="Jump back to footnote [waka] in the text."> &#8617;</a>
</blockquote>
<p>Some more text in here.</p>
```

**Comment by SamyPesse** [comment]
What is your expected result? `markup-it` is outputting the same HTML as some other markdown parser (marked, kramed, etc).

We can probably improve it to always move footnotes at the end of the document.

**Comment by belen-albeza** [comment]
My expectations when using footnotes is that they are:

- Autonumbered  so if I add one later one I don't have to edit them all to change numeration. I'm indiferent about the type of numeration (decimal numbers, greek letters, symbols, etc.).
- At the end of the document
- Definitely not in a blockquote. A numbered list containing all the footnotes of that document, at the end, would be more semantic. And a way to style this list via CSS/theme.

**Comment by tomdavidson** [comment]
@SamyPesse  it is clearly not the same across vendors. Checkout the use case in the [CommonMark demo](https://jonschlinkert.github.io/remarkable/demo/) and pandoc even supports mutliline footnotes so that you can include code snippets without breaking the flow.

[BableMark](http://johnmacfarlane.net/babelmark2/?text=Bla+bla+*blah*%5B%5Ewaka%5D.%0Aand+more+blah+blah+blah+continues...%0A%0A%5B%5Ewaka%5D%3A+Lorem+ipsum+waka+waka+eh+eh~%0Athis+line+is+part+of+the+footnote.%0A%0ASome+more+blah+here+to+check+the+flow) is a pretty slick comparison of 20 some vendors.

While I like the multiline, my expectations with a project such as GitBook would be that footnotes are treated as per the CommonMark spec - non-strict, excatly as @belen-albeza  discribed.

**Comment by gsrohde** [comment]
Here's what I would expect of footnotes:

1. The footnote mark should appear as a superscript (as it currently does), _but the referent in the footnote itself should not._    I see something like this in my footnotes:
> <sup>1</sup>. Footnote text ...

   It looks truly odd to have the number "1" preceding the text of the first footnote appear at superscript level followed by the automatically-added period at baseline level.

2. I agree with @belen-albeza that auto-numbering is an important feature so that if one inserts a new footnote at the top of the document, one doesn't have to re-number all of the existing footnotes.  The existence of plugin "footnote-string-to-number" significantly mitigates this problem.  It seems to me, however, that this is the way things should work by default: I personally don't find much utility in being able to use arbitrary words as footnote marks—I wouldn't normally parse a superscripted "foo" (or any other word) as signifying a footnote.  The main use I can see for being able to use arbitrary text for footnote markers is so that one could use asterisks and daggers and other conventional footnote markers in place of numbers.

3. Using block quotes for footnote text looks quite odd to me.  I'm guessing the motivation for this was to set off footnote text that is placed nearer that point of reference instead of at the bottom of the page (in which case "footnote" is something of a misnomer).  I like the idea of being able to put the footnote text near to the footnote mark in the markup but would prefer that it be rendered as a true footnote—that is, at the bottom of the page (this is the way LaTeX works, for example).

    This "block-quote" rendering is not so awful for short footnotes, but for footnotes that are longer than one line, only the first line is rendered as a block quote, and this looks very odd.  The only way around this that I know of is to put all of the footnote text on a single line in the source text, but this makes certain markup formatting impossible without resorting to HTML tags.

4. It might be nice to be able to have the option to change the footnotes to endnotes (either end-of-chapter or end-of-book) when a book is rendered in PDF format, though this isn't a feature that is that important to me personally at present.

**Comment by gsrohde** [comment]
@belen-albeza I found that I could undo a lot of the objectionable formatting by adding a custom CSS style sheet (in file `./styles/website.css` if for the HTML version).  Here's what I used:
```css
blockquote[id^=fn] {
    border-left: 0;
    padding: 0;
    color: inherit;
}

blockquote[id^=fn] sup {
    top: 0;
}
```
Not ideal and a little hackish, admittedly, but it works well enough for me for now.  One thing this doesn't handle is the positioning of the return link (the arrow).
