### ISSUE TITLE
each include of a git resource results in unique git clone

### ISSUE THREAD

**Issue by mixmix** [GitbookIO/gitbook#1471]
In our book, we use transclusion from other git repos using `{% include .... %}` a lot.

We are mainly including from one other repo, but have noticed (through some logging) that when I run `gitbook serve` that gitbook is cloning the same repo for every single include, even though it already has the repo it needs. 

I desire it to just get each repo once so my build doesn't take 5 minutes (I'm in new zealand)

<3 <3

---

Username : mixmix
Book : https://www.gitbook.com/book/enspiral-academy/kereru-book/details

---

Gitbook : `3.0.3`
OS : Kubuntu 16.04 

SIDENOTE: it's `gitbook -V` not `-v` for version

**Comment by SamyPesse** [comment]
It shouldn't clone the repository more than once ([lib/utils/git.js#L42](https://github.com/GitbookIO/gitbook/blob/master/lib/utils/git.js#L42). 

Your builds are taking ~27 seconds, I plan on investigating GitBook performance issues in the next releases, but I'm closing this issue since git includes are not bottleneck.

**Comment by SamyPesse** [comment]
Sorry! looks like I was wrong (#1472).

I'll take a look at this PR and merge it for next release.
