### ISSUE TITLE
Gitbook serve crashes if temporary files created by emacs disappear

### ISSUE THREAD

**Issue by austinjp** [GitbookIO/gitbook#1500]
### What is the current behavior?

Occasionally my locally-hosted `gitbook serve` will fail with an error similar to:

```
Error: ENOENT: no such file or directory, stat '/home/me/dir/.#filename.md'
```

Files beginning with `.#` are left lying around by emacs. Removing those files manually fixes the issue, if they in fact exist. Occasionally it seems that these files have temporarily existed, then have been automatically cleaned by emacs, leading `gitbook server` to get confused about what files exist. It then deliberately shuts down.

Output from `gitbook version`:

```
CLI version: 2.3.0
GitBook version: 3.2.0
```

Running on Ubuntu 14.04.1.
### What is the expected behavior?

Perhaps generate a warning and ignore the error, carrying on if possible?

**Comment by austinjp** [comment]
Hmm. Manually creating a file of that format with e.g. `touch '.#whatever.md'` fails to recreate this issue.

When it happens again I'll investigate and add more detail.

It's extremely low priority give how easy it is to work around :smile:

**Comment by shigemk2** [comment]
Me neither.

I think there are two solutions.

First, put `(setq create-lockfiles nil)` in our init.el. Then, we can avoid Gitbook serve crash.
Second, fix gitbook's code and send PR. But I am not sure how to debug/build gitbook locally. https://github.com/GitbookIO/gitbook/issues/1435

**Comment by shigemk2** [comment]
This is complex problem.

First, current gitbook would not ignore files whose names start with ".#" just like ".#filename.md" even if we write ".\#*" on .gitignore/.bookignore/.ignore because watcher might watch all markdown files (in watch.js).

Second, current gitbook would fail when gitbook read Emacs lock file because Emacs lock file(like ".#readme.md") is symbolic link file and it doesn't have entity (in node.js).

I sent Pull Request #1722 that fixes second problem.

**Comment by austinjp** [comment]
👍 Nice. I haven't used gitbook for a few months but may need to do so again soon.
