### ISSUE TITLE
Cleaner URLs: Remove html extension from URLs

### ISSUE THREAD

**Issue by akshayrawat** [GitbookIO/gitbook#1540]
Instead of the current -
`https://gitbookio.gitbooks.io/javascript/content/numbers/operators.html`
it would be nice to have URLs without the `.html` extension -
`https://gitbookio.gitbooks.io/javascript/content/numbers/operators/`

And similarly, for links from the sidebar and elsewhere.

CLI version: 2.3.0
GitBook version: 3.2.0

**Comment by franzos** [comment]
Any update on this? A previous issue has been closed #537

**Comment by jackhumbert** [comment]
I'm curious about this as well - it looks like [the fix for #537](https://github.com/GitbookIO/gitbook/pull/1109/commits/096bdaba7aa11d56e0356386faaecb189f3100d4) was merged into the 3.0.0 release, but I'm still seeing the .html behavior using the 3.2.2 builder.

**Comment by AaronO** [comment]
Our next product release (currently beta-testing) no longer uses .html extensions by default :)

**Comment by jackhumbert** [comment]
Great! Thanks for confirming! Happy to beta-test if there's a need :)

**Comment by sashadt** [comment]
@AaronO Any updates on when this might be available?  Wasn't sure if this feature is in `4.0.0-alpha.6`, so I tried to test it, but was not able to due to https://github.com/GitbookIO/gitbook/issues/1706

```
$ gitbook -v 4.0.0-alpha.6 serve
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 14 plugins are installed 
info: 13 explicitly listed 
info: loading plugin "edit-link"... OK 
info: loading plugin "prism"... OK 
info: loading plugin "github"... OK 
info: loading plugin "anchorjs"... OK 
info: loading plugin "versions"... OK 
info: loading plugin "livereload"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "hints"... OK 
info: loading plugin "headings"... OK 
info: loading plugin "copy-code"... OK 
info: loading plugin "theme-default"... OK 
info: found 64 pages 
info: found 407 asset files 
error: error while generating page "README.md": 

TypeError: Parameter "url" must be a string, not undefined
```

**Comment by franzos** [comment]
@AaronO any update on this? I'd love to replace MkDocs with Gitbook but unless I can get clean urls working (without HTML extension), we'd have to rework all support manual references.

Happy to beta-test as well!

**Comment by AaronO** [comment]
@jackhumbert @franzos We're going to allow users to openly request access to the beta and announce it, here's a sneak peek of the new homepage: https://beta.gitbook.com

If you guys want access to the beta could you send me a quick email at `aaron@gitbook.com`, with the following info:
* Org / project name
* Team Size
* Use case (e.g: product docs, api docs, internal team docs)
* Specific features/improvements you're looking to see that

That would be super helpful and I could get you guys setup with the beta today (it's still invite only).

**Comment by xinity** [comment]
Just answered via the Google form :-)

**Comment by sashadt** [comment]
@AaronO, will this feature be available in the product only?  Or will you be adding it to this repository as well?

**Comment by develar** [comment]
@AaronO New beta looks sexy, gitbook is already by default doesn't need to be polished and can be used, but new is more better :)

I have the same question — will this feature be available for gitbook-cli?
Currently, I use netlify to host docs (and netlify CDN automatically converts foo.html to just foo) because... I simply already use netlify and I don't need gitbook hosting / editor (https://github.com/electron-userland/electron-webpack/blob/master/docs/publish.sh). 

Currently, I want to migrate from github wiki to gitbook in another project, so, want to be sure, that gitbook will not abandon ability to generate static site locally.

**Comment by AaronO** [comment]
@develar Url rewriting / "clean URLs" require some kind of host and can't work with plain static files unless you turn every URL into `.../page/index.html`.

So you need something like GitBook's CDN or Netlify's CDN.

The open-source CLI will continue to exist, but not all of our new features fit into that model (editor, drafts, collaboration, ...).

**Comment by develar** [comment]
Netlify doesn't remove `.html` extension from relative links like `../page.html#anchor`. So, it leads to numerous issues — duplicated pages in the search index (Google) and so on.

So, I have forked and fix this issue — https://github.com/develar/gitbook 

Nuxt.js looks like a more better tool to invest (serve, hmr (hot module reload — live editing (if you use IDE instead of gitbook editor)), build to static and so on already implemented), but design, design, design. Gitbook by default produces very amazing result :)
