### ISSUE TITLE
Plugins support for ES6

### ISSUE THREAD

**Issue by urosjarc** [GitbookIO/gitbook#1602]
Please add es6 support for anonimous function syntax. `this` object is empty in `page` hook.

```javascript
'use strict';

module.exports = {
    hooks: {
        'page:before': function (page) {
            console.log('\n> Working...');
            console.log(Object.keys(this));
            console.log('---------------------------');
        },
        'page': (page) => {
            console.log('> Not working...');
            console.log(Object.keys(this)); //Empty
            console.log('---------------------------\n');
        }
    }
};
```

**Comment by simonkberg** [comment]
This is how Arrow Functions work - they don't bind their own context. They are not a replacement for normal functions, but a new type of functions introduced in es2015. They are not suitable for use as object methods due to their lack of implicit bindings.

Please refer to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) for more info.
