### ISSUE TITLE
How to get custom footer and header for pdf (ebook) ?

### ISSUE THREAD

**Issue by cloudyuga** [GitbookIO/gitbook#1661]
### What is the current behaviour?

I would like to get custom footer and header. I do following
```
$ gitbook init
$ mkdir ebook
$ echo "Page{{ page.num }}  - <b>CloudYuga Technologies</b>" > ebook/pdf_header.html
$ echo "Page{{ page.num }}  - <b>CloudYuga Technologies</b>" > ebook/pdf_footer.html
$ gitbook pdf ./ ./mybook.pdf
```

I don't see custom header and footer in my pdf. 

  - Provide the GitBook version being used (`gitbook -V`)
```
CLI version: 2.3.0
GitBook version: 3.2.2
```
  - Provide system informations (OS and version)
```
Mac
```

### What is the expected behavior?
I should see custom header and footer.

**Comment by cloudyuga** [comment]
By look at an example [here](https://github.com/markomanninen/creativepowerofthefloweroflife) I was able to get custom header and footer. Thanks @markomanninen.

Can we put a logo on the header/footer.

**Comment by markomanninen** [comment]
Glad you found it helpful. If I remember right, footets didnt go thru normal page processing so image tags there wont be stored lically first, as they work on normal pages. You can try to find out how gitbook uses locally stored pictures in pdf and mimic that. I would also try to use base64 encoded embedded img tags. Images should also be in print dpi 300 resolution so that their quality is acceptable on final output.

**Comment by shreeve** [comment]
How are custom headers and footers added to PDF files? What is the process to merge the custom header and footer and overlay them onto the content page. Is there a utility such as `cpdf` or something similar that actually does the merging of the header/footer for each page? From what I understand, this cannot be done purely with HTML/CSS unless you use a tool like `PrinceXML` to generate the output PDF files.

How does the custom header/footer get merged to content pages when generating PDFs?
