### ISSUE TITLE
how to add a <meta> tag in <head> tag for every page?

### ISSUE THREAD

**Issue by kiwenlau** [GitbookIO/gitbook#1668]
I want add a \<meta\> tag in every page of the generated html files

```
<meta name="baidu-site-verification" content="GlKB0OINL3" />
```

I tried to write a plugin according to #1100 , but failed...

```
module.exports = {
    website: {
        html: {
             'head:end': function() { return '<meta name="baidu-site-verification" content="GlKB0OINL3" />' }
        }
    }
};
```

**Comment by nagim** [comment]
Have you tried adding it in the YAML frontmatter?

**Comment by kiwenlau** [comment]
how to use YAML frontmatter? In addition, I'm still interested in implementing a plugin...

**Comment by nagim** [comment]
Sorry, I just saw that you want to include it in every page. In this case it's not an efficient solution, since you have to insert it on every page.

Instead, you can try extending the theme by creating _layouts/website/page.html file in your repository.
Inside the page.html, you can extend different parts of the html. It will be applicable to every file.
See here for description: https://toolchain.gitbook.com/themes/

**Comment by kiwenlau** [comment]
Thank you for your help! But I prefer to write a plugin.... It should be easy

**Comment by nagim** [comment]
If you check the plugin in referenced in #1100, you can notice that it uses the same method I outlined:
https://github.com/denysdovhan/gitbook-plugin-rss/blob/master/_layouts/website/page.html

Hope it helps!

**Comment by kiwenlau** [comment]
I've figured out how to do it. THX~

**Comment by Shahzzoda** [comment]
How did you do it? @kiwenlau

**Comment by wangyi7099** [comment]
@Shahzzoda 
In you `page.html`, add this code:
```html
 {% block head %}
    {{ super() }}
<script src="XXX"></script>
{% endblock %}
```
