### ISSUE TITLE
I am in serious trouble. I erased master accidentally. Can I restore erased master?

### ISSUE THREAD

**Issue by helo717** [GitbookIO/gitbook#1693]
The erased gitbook is here.
https://www.gitbook.com/book/convibase/userguide/

I want to restore other branch without breaking it.

Help me. Please.

**Comment by AaronO** [comment]
@helo717 I've restored your `master` given the last know built commit https://www.gitbook.com/book/convibase/userguide/build/584a6e4c1cb27d1000d507fa.

Your `master` now points to `6d5c5cd767fa9508eb46a35d6ccf9f0b03c4700e`

Let me know if that's good. In the future since you're communicating regarding private content, please reach out via our contact form https://www.gitbook.com/contact, this will avoid you leaking potentially confidential private info on GitHub.

**Comment by helo717** [comment]
Thank you very much. There is no more thankful words. Thank you very much for helping me.
