### ISSUE TITLE
Oh man,what's wrong with gitbook?

### ISSUE THREAD

**Issue by EasonWang01** [GitbookIO/gitbook#1700]
Are you give up for solving the issue on gitbook?

Why new version lags and frequently crashed???

**Comment by Mackiovello** [comment]
Just a polite reminder. Posting a ton of issues with very little information will not solve the issue. If you want this to be resolved, you should at least provide some information. There's is no way for the GitBook people, who are doing a great job, to resolve something that lacks specifics. It should also be enough to have one issue. Right now, you have three issues with very little information: #1678, #1686, and this one.

Have you tried on another machine to isolate that it's GitBook and not your computer?

**Comment by KINGSABRI** [comment]
> Are you give up for solving the issue on gitbook?
>
>Why new version lags and frequently crashed???
@EasonWang01 

Ok, let me explain some things, 
After my full satisfaction with 4.x version and how stable and fast this version was, Gitbook released version 5. x which was (IMHO) a disaster to me, and to my book. 

Version 6. x came with new UI and somehow new structure and features (especially the document mode) which are a lot of implementations here and its buggy(much better now 6.6.2) and slow(tell the moment).

I was really angry about this and disappointed, especially when they release a new version with new features without fixing the existing issue, just like you I was really upset. 

In other hand, those people are working so hard, reply so politely and patiently. They fix things as fast as they can. I believe  Gitbook is a running business for them so they're eager to be more perfect than anyone here. 

For me, I believe without Gitbook I don't think my book will be presented this way and get popular this far. I know I expected more from Gitbook because I respect them and I believe they can do what I wish to have. 

With that being said, let's show those people some respect and give them informative descriptions about our issues (they already have a template for that)

Final word for the awesome people in Gitbook, please consider more priority for bug fixes, people love you and expect more.

I hope my word didn't hurt anybody. 
_Regards and respect_

**Comment by HienNguyen711** [comment]
I have just come back Github after 5months. My experience 5 month ago is good with Gitbook. But now, it is so bad. I did not realize about it and spend almost a day wasting my time with it. It saved already but when you reload, it disappear everything. After using it in about 30min , the title of the book is disappear. There are so many problems, it just ruined my whole day and wasting my time. I hope for a better fixing.
