### ISSUE TITLE
SSH support for gitbook desktop editor

### ISSUE THREAD

**Issue by Bhushan001** [GitbookIO/gitbook#1716]
Hi All, 
I would like to know if there is ssh support available for gitbook currently or not? 

Scenario:
I have deployed my gitbook on cloud environment. I can login to this system using ssh.
Now I would like to know if I can configure my gitbook desktop editor with ssh so that it can make changes directly to this remote repository?

Thanks.

**Comment by anxiaoyi** [comment]
I also want to know whether or not gitbook support

**Comment by Bhushan001** [comment]
is this repository even maintained on github? if they have moved it to other source then please refer me.
thanks

**Comment by AaronO** [comment]
@Bhushan001 @anxiaoyi What's your use case ? Why do you need SSH support ? Do you use `gitbook.com` ?

**Comment by anxiaoyi** [comment]
I want to publish book in terminal 

AaronO <notifications@github.com>编写：

**Comment by Bhushan001** [comment]
yes.. below is my scenario... I have installed gitbook editor on my mac.. and I have cloned my gitbook repository on remote server i.e. some docker container or any cloud based OS. Now I want to make changes to that repo from my mac. i.e. I want gitbook editor to use ssh to access that repository on that host. hope I have explained my case clearly.. I need guidance on is there any functionality that I am not aware of or is it not implemented ? also if not, what could be the approach if I try to do this ? 
Thanks

**Comment by AaronO** [comment]
@Bhushan001 Ok so your content is on a custom SSH server of yours, not `gitbook.com`, correct ?

We don't support `SSH` on `gitbook.com` because `HTTPS` is a better transport in most scenarios, we can use api, oauth tokens and std basic auth, without users having to worry about configuring and setting up clunky keys whilst being equally secure.

Since we don't support it on `gitbook.com` it's not supported in the Desktop Editor.

**Comment by Bhushan001** [comment]
@AaronO  what would you recommend then ? using https or should we go for ssh support if there is possibility in near future for gitbook to use ssh ?

**Comment by AaronO** [comment]
The editor supports git over https since that's what it uses when you use GitBook.com

**Comment by Bhushan001** [comment]
so ssh support will not be possible for gitbook editor.right?

**Comment by AaronO** [comment]
@Bhushan001 It is possible, it's not super hard technically. It just doesn't make product sense for us to spend time on it.

Since it's easier to use `gitbook.com` to host repos, auth over api/oauth tokens and not worry about SSH being blocked by firewalls, configuring and ensuring all users understand the concepts of SSH keys etc ...

Why do you not use `gitbook.com` ?

**Comment by Bhushan001** [comment]
@AaronO we are using that . :) still if want ssh support , would you recommend any steps?

**Comment by AaronO** [comment]
@Bhushan001 Cool, it wasn't clear from your previous messages since you didn't confirm.

There's an article here that explains how to use the `git` CLI with `gitbook.com`: https://help.gitbook.com/books/how-can-i-use-git.html

Take a look "Saving your credentials" and API tokens specifically if you don't want to store your password in clear in your `~/.netrc`.
