### ISSUE TITLE
Cannot Integrate Gitbook organization with repo owned by Github organization

### ISSUE THREAD

**Issue by oshoma** [GitbookIO/gitbook#1796]
### What is the current behavior?
I tried connecting my Gitbooks organization to my github organization. The first OAuth step works OK but I do not land on a page for granting access to my repositories, as shown in step 2 here: https://help.gitbook.com/github/can-i-host-on-github.html.

After the initial OAuth step, when I go to the GitHub tab in my Organization page on gitbooks I see the "Install Github integration on this account" button is disabled and the Books section is still empty, with the text "Your books linked to GitHub will be listed here once the GitHub integration has been installed on this account."

I click "Select a GitHub organization" and the dialog shows the name of my github org `dive-networks`, with the text "Github admin permissions required". However the entire dialog is disabled.

My gitbooks user name: oshoma
My gitbooks org name: @dive 
I'm running on a recent Macbook, OSX 10.10.5, Chrome 58. Also repro's on Safari.

### What is the expected behavior?
I should be prompted to select repositories as shown here https://help.gitbook.com/github/can-i-host-on-github.html.

**Comment by billy3321** [comment]
I have this problem too.

I already grant gitbook the permission to access my organization, but when I select the github repo at gitbook setting, I can select my own repo only, I cannot select the repo of the organize, because it didn't show.

**Comment by aborruso** [comment]
Me too!

**Comment by mistyharsh** [comment]
I was facing the same issue. Finally, I figured it out. It is not that straightforward.

Step 1: Sign In to Gitbook and go to setting page. Click on Github tab as shown below:
![image](https://user-images.githubusercontent.com/4905303/27043951-7c674bde-4fb9-11e7-9572-1f94da49fdbf.png)

Step 2: Once you click on blue button to install GitHub integration. You will be taken to the following screen:
![image](https://user-images.githubusercontent.com/4905303/27044118-2227c184-4fba-11e7-8900-a3924cd2738d.png)

Step 3: **This step is important**. By default, GitBook will attempt to install app to your personal account. This is not what we want. We want to install it with the organization so that we can use repositories that are part of the organization. On above snapshot you should click **cancel** button instead of install button. This will take you to the following UI:
![image](https://user-images.githubusercontent.com/4905303/27044232-7abbb3be-4fba-11e7-8330-95af5d763132.png)

Step 4: Now you can choose your organization and select your organizational repositories.

Also, make that you have already granted access to GitBook at organizational level before you perform these steps.

**Comment by jfgrissom** [comment]
I setup a repo in github on my personal account but really would like it to be in an org. Anyone know how to do this with the current version of gitbook?

**Comment by HQarroum** [comment]
I faced the same issue and finally found way to get it an integration between Gitbook and a repository within an organization I own. Here's what I did.

 1. Enable the GitHub integration in your GitBook project and go to the point where your repositories are listed by GitBook. At this point, you won't see your organization.
 2. Go to your GitHub account settings under the **Applications** menu.
 3. Select the **Authorized OAuth Apps** tab.
 4. Search for **GitBook* and click on it.
 5. In the **Organization access** section of the page, the organization which does not appear in GitBook should show up with a red cross on it. Click the *Grant* button (the button is actually buggy so you'll have to reload the page after having clicked on it for the state to refresh).
 6. Go back to GitBook and re-initiate the GitHub integration to force GitBook to re-query your list of repositories from GitHub.
 7. Your organization should appear now.
