### ISSUE TITLE
Is anybody behind gitbook system receiving support emails?

### ISSUE THREAD

**Issue by alexandernem** [GitbookIO/gitbook#1799]
I've not received any reply on my issue, that I sent through site support form. Please contact me if you have any questions, we are payed customers, I hope there will be some support from the gitbook team.
We are permanently receiving "Update Failed" emails and can't get reason why the commit has failed, in this situations some of our work is lost.

alexander.nemsadze@azry.com

`Update Failed
The update (master/b3a6d2b) of your book "*** User Gude" has failed after 31.043 seconds.
Access your update details to fix it and publish a new version.
Having trouble? Check out the list of common errors.`

**Comment by nagim** [comment]
Hi, 

In order to be able to help, please check the logs of your build.
Going into your book's properties on the GitBook GUI (not the editor), there's a tab *XX Updates*. Clicking on it will give you the list of builds/updates. Click on the commit hash (character series on the right hand side) of the latest update, that will guide you to the log. Please paste it here, it will be muh easier.

Thanks,
Imre

**Comment by alexandernem** [comment]
Thanks for the response.

Error logs shows following:


info: found 3 pages 
info: found 2 asset files 
error: error while generating page "chapter1/.md": 

FileNotParsableError: "chapter1/.md" file cannot be parsed

How can we see what parsing error occurred? Files are occasionally big, with some information copy pasted from other places.

**Comment by nagim** [comment]
It seems you have a bad filename `.md` in the `chapter1` folder. Or it is possible that the `SUMMARY.md` contains this incorrect file reference.
