### ISSUE TITLE
[BUG] Unable to add discussions thread to bulleted text items

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/gitbook#1921]
### What is the current behavior?

It is possible to create new discussions for plain text in paragraphs.

It is not possible to initiate a discussion for text in bullets, text in tables, etc.

### What is the expected behavior?

I see no logical reason for restricting reader from being able to leave comments for arbitrary text elements.

**Comment by AaronO** [comment]
Most content can be commented on in the new versions:
- paragraphs
- lists
- images
- code blocks
- embeds (youtube videos, github gists, codepens, ...)
- etc ...

We haven't enabled commenting on some elements like tables / api methods, because we haven't clearly figured out a good UI / UX (e.g: should one comment on individual cells or the table as a whole).

![image](https://user-images.githubusercontent.com/949223/32968147-72e6d39c-cbe0-11e7-8c8a-eda95ffdbbc6.png)

Closing this issue since it is implemented in the upcoming release.

**Comment by fedorov** [comment]
What is the transition timeline?

Will migration of the existing gitbooks happen automatically?
