### ISSUE TITLE
can not see the menu from the phone

### ISSUE THREAD

**Issue by gHashTag** [GitbookIO/gitbook#1998]
#### Example

![image-1-1](https://user-images.githubusercontent.com/6774813/37283243-51e74988-2608-11e8-9acc-307e7d46460d.jpg)

**Comment by norbertfuhs** [comment]
Hi I'm just a Gitbook user and I think I found an plugin that solves your problem here:

[https://github.com/Goopil/gitbook-responsive-table](https://github.com/Goopil/gitbook-responsive-table)

Please note that Gitbook is currently beta testing a new version of Gitbook you can check it with this link:

[https://beta.gitbook.com/](https://beta.gitbook.com/)

I hope this helps if so please close this issue if not feel free to add another comment.

**Comment by gHashTag** [comment]
@nasirkhan Thanks, but why after installing the plugin menu is all the same (

**Comment by norbertfuhs** [comment]
Okay sorry I will try to find a solution for this and comment it as fast as possible

**Comment by norbertfuhs** [comment]
This screenshot was taken from an iPhone 6 Plus with the resolution of (1242×2208) right?

**Comment by norbertfuhs** [comment]
I tested this with several resolutions with the current Gitbook 3.2.3 and got the same problem.

However with Gitbook v4.0.0 the problem was gone... did you try to reach the team behind Gitbook via their Slack Channel? [https://slack.gitbook.com/](https://slack.gitbook.com/)

**Comment by norbertfuhs** [comment]
@gHashTag did you take a look a this issue ? [#1530](https://github.com/GitbookIO/gitbook/issues/1530)

This issue seems to be an duplicate an gone with v2 of Gitbook.
