### ISSUE TITLE
Custom Theme, Installing from GitHub

### ISSUE THREAD

**Issue by martindale** [GitbookIO/gitbook#2055]
After many attempts to customize the theme, it seems `gitbook` and `gitbook-cli` are restricted to installing from NPM, as opposed to installing from a specific GitHub repository (_a la_ `npm install martindale/gitbook#custom-branch`, for example).  This severely restricts customizability and makes it difficult to develop themes.

I've dug through the documentation, and it seems like even publishing a `gitbook-plugin-theme-*` package to NPM fails to replace the theme, and instead continues to install `default-theme` regardless of what options are specified in `book.json`.  Please advise!

**Comment by martindale** [comment]
See also gitbookio/gitbook-cli#5 and #710.

**Comment by kiwi0fruit** [comment]
Here https://github.com/kiwi0fruit/ultimate-question/blob/master/publish_gitbook.bat I use forked and tuned default theme and install it right from GitHub. Then upload generated static Gitbook to the GitHub Pages.

In order to make install from GitHub work I needed to build and add `_assets` to the repo https://github.com/kiwi0fruit/theme-default
