### ISSUE TITLE
Template render error: unknown block tag: page

### ISSUE THREAD

**Issue by xingjianhui** [GitbookIO/gitbook#2089]
Version:
CLI version: 2.3.2
GitBook version: 3.2.3

Error:
```
$ gitbook build
info: 15 plugins are installed
info: 7 explicitly listed
info: loading plugin "redirect"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 68 pages
info: found 0 asset files
error: error while generating page "introduction.md":

Template render error: (/apps/growingio-docs/introduction.md) [Line 11, Column 2]
  unknown block tag: page
```
I try other gitbook version 2.6.6 
it give me the same error

Thanks

**Comment by ipy** [comment]
We are facing the same problem. Since gitbook.com is not well accessable in China, we need to publish a readonly copy of the docs to our developers on our own server.
This issue is caused by the {% page-ref %} tag. I guess we are missing some plugins. Could someone share the settings used by gitbook.com so we can publish the book edited on gitbook.com?
