### ISSUE TITLE
GitBook Web Site Unavailable in Eastern Europe

### ISSUE THREAD

**Issue by nakov** [GitbookIO/gitbook#2124]
I am trying to **open https://www.gitbook.com** and **login**. Login works correctly from United States, but **fails from Bulgaria and Eastern Europe** (due to Cloudflare issues). The error message says "522 Connection timeout" after very long wait period (2-3 minutes):

![image](https://user-images.githubusercontent.com/1689586/45756013-7906c280-bc28-11e8-82e4-704894146f74.png)

### What is the current behavior?

Logins says "timeout", reported by Cloudflare, when I login from Eastern Europe (my IP address is 217.174.159.227):

![image](https://user-images.githubusercontent.com/1689586/45756253-1c57d780-bc29-11e8-9b19-a9ee23bad1f7.png)

### What is the expected behavior?

Successful login:

![image](https://user-images.githubusercontent.com/1689586/45756136-c7b45c80-bc28-11e8-8c29-1c49fcfae415.png)

The above screenshot is taken from a virtual machine, located in the United States (IP 35.224.5.122).

**Comment by nakov** [comment]
Looks like the **Cloudflare firewall blocks the IP addresses** from Eastern Europe.

Is this **intentional** behaviour?

**Comment by SamyPesse** [comment]
> Is this intentional behaviour?

No

We are working with Cloudflare / Fastly / Google Firebase to fix this issue. Basically some IPs from Eastern Europe servers of Fastly/Firebase are not accessible by Cloudflare.

**Comment by nakov** [comment]
Any updates here?

Do you recommend to **migrate to https://readthedocs.org**, which is not broken?

The SoftUni Foundation has 7 open source books in GitBook Legacy and we are blocked of working on them, updating the content and rebuilding them. We need to update the content.

Now the legacy GitBook build system is broken, and the new GitHub system is unavailable. What is your solution?

**Comment by nakov** [comment]
Hey, guys, shall **anyone fix this issue**?

I paid for an account for GitBook and I still cannot access and use it.

**Comment by nakov** [comment]
This is my next reminder to fix this issue. I have paid to use GitBook and I cannot use it because it is unavailable from Bulgaria. Shall I migrate to https://readthedocs.org?

**Comment by SamyPesse** [comment]
@nakov To give you more context: the issue is Fastly blocking some IPs from Cloudflare edges (that are located in Russia and Bulgaria).

We are working on a solution to bypass Fastly, and only use Cloudflare. It should solve these issues.

But I can't give you an ETA.

**Comment by nakov** [comment]
Thanks, I will find a contact at Fastly to help resolving this. The world is small and my former students work everywhere, highly concentrated in the SF Bay Area :)

**Comment by nakov** [comment]
I performed some debugging. This URL cannot load from Bulgaria (522 Timeout) but loads successfully from France (200 OK):

`https://www.gitbook.com/public/js/manifest.a15f3541.js`

The HTTP headers reveal a lot of debug info:
```
access-control-allow-origin: *
cache-control: public, max-age=604800, s-maxage=1209600
cf-cache-status: MISS
cf-ray: 47675ce529962b82-AMS
content-encoding: br
content-type: text/javascript; charset=utf-8
date: Thu, 08 Nov 2018 10:30:12 GMT
etag: W/"86e46ff485c7f6a68fad65795c0c7a16"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Wed, 07 Nov 2018 21:04:18 GMT
last-modified: Tue, 06 Nov 2018 16:10:37 GMT
server: cloudflare
status: 200
strict-transport-security: max-age=31556926
vary: Accept-Encoding
via:1.1 varnish
x-cache: HIT
x-cache-hits: 1
x-goog-generation: 1541520637051506
x-goog-hash: crc32c=XHdEpA==, md5=huRv9IXH9qaPrWV5XAx6Fg==
x-goog-metageneration: 1
x-goog-storage-class: MULTI_REGIONAL
x-goog-stored-content-encoding: gzip
x-goog-stored-content-length: 1018
x-guploader-uploadid: AEnB2Uq_kjYxGLgNwevfCIcj8JHZi3fSaVYXVUBV1JDkSc01MZnamC33Rss2w4j09Z71i-e8KBg1vy4B8UlugKKMfV0ja9SZNw
x-served-by: cache-ams4439-AMS
x-timer: S1541673012.043726,VS0,VE1
```

This is static content (JS code), stored at **Google cloud storage**, served by **Varnish-Cache**. It looks like Fastly is somehow involved, but the problem might come from Google Cloud as well or from Varnish.

I am in a contact with a senior technical expert working in Fastly, but he needs more detailed technical information: **which IP** exactly is failing to contact **which endpoint at Fastly** (IP / port / URL).

Do you have this information?

**Comment by AaronO** [comment]
As a side note, you can see Cloudflare's IP ranges here: https://www.cloudflare.com/ips/

**Comment by nakov** [comment]
They don't have solution. Now the legacy GitBook is broken and the only solution is migration to ReadTheDocs.

I still use the Legacy GitBook with a lot of heavy obstacles and I am looking for a migration path.

Maybe I will install a local GitBook build toolchain.

**Comment by AaronO** [comment]
@dinamic @nakov This is caused by an issue between Fastly/Firebase and Cloudflare. I spent weeks (months?) talking with them and they basically concluded that it's a "no fix" for them ... (which is very disappointing)

So I built an experiment to bypass Fastly and replace Firebase Hosting's layer with a Cloudflare Worker. That bypass is functional and running in staging.

The main challenge is that it's hard for us to reproduce (since we aren't in Bulgaria) and since we can't reproduce it we can't ensure that the bypass we've put together fully fixes it too.

We could deploy the bypass in production, but it would be ideal to confirm that it's a real fix first.

**Comment by AaronO** [comment]
@nakov @dinamic I tried reproducing this by using a VPN (from Bulgaria), but I get routed to Budapest and it works for me.

Could you share the IP of the cloudflare edge you're connected to ?
1. You should be able to get it from the chrome inspector's network tab
2. Or by doing `dig www.gitbook.com` in your terminal

That would help because it might allow us to simulate/force routing dev traffic through Cloudflare's sofia edge(s).

**Comment by AaronO** [comment]
@nakov @dinamic Quick follow-up. I was able to get a proxy in Sofia and reproduce the error.

I get the same error in staging that you guys get in production if I de-activate the bypass, and it works if the bypass is active.

Now that we can reproduce this and reliably test it, we should be able to move towards deploying the Fastly / Firebase bypass in production.

**Comment by nakov** [comment]
Hi Aaron, thanks to working on this issue. My local CloudFlare edge IP is: **104.25.212.20**.

Still, I cannot open www.gitbook.com from Sofia. My current IP is: **176.12.22.58**.

Let me know if you need a proxy / VPN in Sofia. I can setup one for you.

**Comment by nakov** [comment]
> @nakov @dinamic Quick follow-up. I was able to get a proxy in Sofia and reproduce the error.
> 
> I get the same error in staging that you guys get in production if I de-activate the bypass, and it works if the bypass is active.
> 
> Now that we can reproduce this and reliably test it, we should be able to move towards deploying the Fastly / Firebase bypass in production.

Thanks. I am looking for the next steps from your side.

I use GitBook almost every day and I will be happy to move from legacy.gitbook.com to gitbook.com instead to readthedocs.com (which I use for my latest projects).

**Comment by nakov** [comment]
> Now that we can reproduce this and reliably test it, we should be able to move towards deploying the Fastly / Firebase bypass in production.

Do we have progress about this Fastly / Firebase bypass in production?

I still cannot use new **gitbook.com** site and the **legacy.gitbook.com** is now broken (does not synchronize with GitHub), so my books cannot be changed.

**Comment by NikolayIT** [comment]
Same here. When will this be fixed?

**Comment by mdamyanova** [comment]
I'm from Bulgaria and I have the same problem.

**Comment by AaronO** [comment]
@nakov @NikolayIT @mdamyanova The bypass (which will fix the issue) has been coded, but not yet deployed.

You can see it here: https://github.com/GitbookIO/firebase-on-cloudflare

We haven't yet had time to deploy fully test it before deploying it (since it will impact all traffic going to `www.gitbook.com`)

**Comment by erogleva** [comment]
I am from Bulgaria too and can't open GitBook either

**Comment by VaskoViktorov** [comment]
Same problem, same location. Are you going to fix this ?

**Comment by mchaov** [comment]
You know this is not the only book affected, right? :)

**Comment by BerdyGaming** [comment]
When will this ever get fixed? This was first reported 151 days ago, that's almost half an year. Will you even bother to give us some sort of an update on the situation?

**Comment by SamyPesse** [comment]
The issue was coming from Cloudflare and Fastly blocking each others.

🚀 Today, we've deployed a major changes to our infrastructure that should have fixed it:

- Static files are now served directly by Fastly under `static.gitbook.com`
- Web pages are now served by Cloudflare without requesting Fastly

It took a long time because it requires to rethink our architecture.

It should be working as expected, and it does according to our tests using proxies. Let us know if you still have issues.

**Comment by nakov** [comment]
I confirm that the problem is now fixed.
Thanks, GitBook dev team!
