### ISSUE TITLE
Type 'Timer' is not assignable to type 'Timeout'.

### ISSUE THREAD

**Issue by Justman100** [GitbookIO/gitbook#2355]
## Bug description
Get only this:
![grafik](https://github.com/GitbookIO/gitbook/assets/149507651/ba7de437-59e4-4ff9-8d04-3e9e6f19f2e8)

## How to reproduce
```sh
git init
git pull GitbookIO/gitbook
bun install
bun next build
```

**Comment by Justman100** [comment]
@jpreynat

**Comment by jpreynat** [comment]
@Justman100 A fresh install works for me.

After looking around quickly, it looks like the `Timer` type that you got for `setTimeout` could come from bun's types, while the one I got and that's used at compile time is the `@types/node`'s module one.

Might be good to check that you use the same version of bun as I am, `1.1.17`, but otherwise I'm not sure what's wrong.
Just as an additional clue, if the build from scratch was actually failing, our PRs and `main` branch deployments to Cloudflare Pages would fail too. I'm thus closing the issue and I encourage you to look at your local configuration.

**Comment by Justman100** [comment]
> After looking around quickly, it looks like the `Timer` type that you got for `setTimeout` could come from bun's types, while the one I got and that's used at compile time is the `@types/node`'s module one.

And how do I change that?

> Might be good to check that you use the same version of bun as I am, `1.1.17`, but otherwise I'm not sure what's wrong. Just as an additional clue, if the build from scratch was actually failing, our PRs and `main` branch deployments to Cloudflare Pages would fail too. I'm thus closing the issue and I encourage you to look at your local configuration.

Is that a joke? Two minor versions in just 3 days? But no, the latest version has the same error!
