### ISSUE TITLE
Feature: SUMMARY.md per a chapter

### ISSUE THREAD

**Issue by ismaild** [GitbookIO/gitbook#297]
Currently with Gitbook you define your book structure in _SUMMARY.MD_. The entire book structure is defined here, with each chapter having a dedicated folder within your repo. 

Another way to consider would be to include a _SUMMARY.md_ per a chapter. 
- Your summary at the root, defines your chapter structure
- Your summary in each chapter, defines your articles

The advantage of this is if you would like to generate a single chapter into an ebook/pdf etc. You can. Right now i have written some scripts to generate a _SUMMARY.md_ 

This has other use cases, while strictly not for books it could be used for Magazines/Newsletters etc.

**Comment by jerger** [comment]
I realized this at my book ... but its a little bit tricky, as u can see here: 
https://github.com/DomainDrivenArchitecture/ddaArchitecture/tree/master/en and 
https://github.com/DomainDrivenArchitecture/ddaArchitecture/tree/master/en/30_requirements

**Comment by jerger** [comment]
Found this feature works only till version 2.6.7 :-(

**Comment by maxkoryukov** [comment]
Such feature will be very useful for me;) I don't want to have huge `SUMMARY.md` in the root, but having an toc-file in subfolders - it is very convenient.
More over, I will be able to **generate** content with its own _TOC_ for several folders.

On other hand: you could use `include` for **gitbook < 3.2.0** (because of this bug: #1504)
