### ISSUE TITLE
Read .Rmd files too?

### ISSUE THREAD

**Issue by stevepowell99** [GitbookIO/gitbook#307]
I can't find a way to get gitbook to recognise custom filetypes. It would be great if there was an option for gitbook to treat .Rmd files exactly as it does .md files, see http://rmarkdown.rstudio.com/. This would be a useful workaround to enable citation support by using Rgitbook.

**Comment by maxheld83** [comment]
agreed this would be fantastic, especially since the development on https://github.com/jbryer/Rgitbook seems to have stopped, and https://github.com/rstudio/rmarkdown is only accelerating.
I can see some potential for science customers like myself ...

**Comment by SamyPesse** [comment]
I can add the `.rmd` extension so that it would be parsed as markdown, is that what you want?

Or do you want a supporte of rmarkdown inside GitBook ? (I don't think it's a great idea to add another "markdown" inside gitbook for now)

**Comment by maxheld83** [comment]
No, I don't think there's a need for another *editor* – agreed.
I was thinking it would be nice if I could have GitBook invoke the Rmarkdown functions whenever I push a commit to Github, so that I wouldn't have to manually create the markdown version from rmarkdown and push it (again).
Not sure how feasible it is to have R run in the background on your server though ...

**Comment by SamyPesse** [comment]
The best would be a gitbook plugin that use the `init` hook to generate the markdown from the `.rmd`.

I'll look at how feasible it is.

**Comment by maxheld83** [comment]
great. Your work and the pace of development here on gitbook.io is impressive!

**Comment by znmeb** [comment]
I'm hacking on this stuff too in my spare time - I was unaware of RGitbook until I read this thread!! ;-) 

As I've noted in other threads, my approach is to render .rmd to .md using RMarkdown / knitr and then do the rest with GitBook. However, I don't have any actual chapters yet to see how they look. So stay tuned. Meanwhile I'll go look at Rgitbook and see what I can do with it.

Incidentally, since the GitBook toolchain has Calibre already, another strategy would be to make EPUBs from RMarkdown / Markdown via Pandoc and then have *Calibre* do the PDF conversion. I don't know how Calibre-generated PDFs look however - fonts might be an issue.

**Comment by dpastoor** [comment]
@SamyPesse fyi, giving an init hook to render the rmd to markdown would be completely infeasible on the server as you'd also need to maintain copies of the required packages and versions people are using in their R analysis. A better option would be to directly leverage the rmarkdown/knitr package(s) to knit2markdown then have the already-rendered markdown ready to push to github.

To get an idea of hooking knitr to output processed Rmarkdown you can also take a look at https://github.com/swarm-lab/editR which is a live update to render written markdown into html (the difference is in this case you'd want to use the knit2markdown rather than knit2html

**Comment by maxheld83** [comment]
@dpastoor , thanks, you're completely right and I don't know why I didn't think of that – indeed, having gitbook run all the R stuff is nuts, also because then you'd have upload the actual *data* somewhere. Fuzzy thinking on my part.

I agree that it would make a lot more sense to accomplish this via another `Rmarkdown` output format (development info [here](http://rmarkdown.rstudio.com/developer_custom_formats.html)).

Ideally the function could look at some `index.md`, from where all the `child` documents are called, and infer a `SUMMARY.MD` from there.

**Comment by znmeb** [comment]
> I agree that it would make a lot more sense to accomplish this via another Rmarkdown output format (development info here).

RMarkdown can translate an rmd file directly to any dialect of Markdown you can specify in Pandoc - indeed, to any output Pandoc can write! The only tricky part is getting it rendered during your authoring process. See http://rmarkdown.rstudio.com/markdown_document_format.html for the details.

What I usually do is render to HTML while authoring and then switch my `_output.yaml` file over to Markdown when I'm happy with how things look.

**Comment by maxheld83** [comment]
If I am getting this right, the more feasible option for support for `*.Rmd` projects would be to have a format inside of [Rmarkdown](https://github.com/rstudio/rmarkdown).
I opened up an issue to that effect over on RMarkdown and would love some feedback/suggestions on that -> https://github.com/rstudio/rmarkdown/issues/394

**Comment by maxheld83** [comment]
*Reading* in `*.Rmd`, as this issue originally suggested seems to be beside the point, on second thought (because it makes not sense to run R through gitbook, let alone on their servers).

Instead, it would be nice to go at this from the other end: to have RMarkdown export a directory ready for Gitbook.io -> https://github.com/GitbookIO/gitbook/issues/645

**Comment by dpastoor** [comment]
@maxheld83 yes the easiest implementation will be to have 3 subfolders in the main project folder - rmdbook, mdbook, and the autogenerated _book from gitbook. The workflow, as I imagine, would be to do all editing in the rmd files, then similar to how you can `devtools::document()` for roxygenizing your documentation, you would `render_book()` which would automatically render all Rmd's to markdown in the mdbook folder. From there you could call something along the lines of `create_book()`. 

This would also make it "easy" to do things like auto check for diff's between the md and Rmd versions and only re-render the rmd files that have changed, etc. Eventually, could likely hide the intermediate mdbook folder, but makes it much easier to troubleshoot and simplifies the build process.

I started a repo `lpgitbook` (literate-programming gitbook) but realized I was unsure of some of the gitbook build processes (eg is the summary created automatically or does the user need to create that) so its not functional at all the moment, but hopefully I'll get some time in the future to work on it.

**Comment by maxheld83** [comment]
exactly @dpastoor that's what I thought.
Sounds exciting that you got started on a function already (I hope to have some time to work on this over the summer).
One addition: I thought it might be neat to have the output directly commited to a different *branch*, ideally the HTML to the `gh-pages` branch, that way, you would be able host from the repo *directly*.

**Comment by stevepowell99** [comment]
sounds perfect. Would be also great to have the ability to slot in a custom
preprocessing function before the main render_book kicks in, e.g. a custom
filter, i.e. render_book("myFolder","myCustomPreProcessingFunction", ...).
Am interested in testing anything you manage to come up with.

On Fri, Mar 13, 2015 at 3:36 PM, Devin Pastoor <notifications@github.com>
wrote:

> @maxheld83 <https://github.com/maxheld83> yes the easiest implementation
> will be to have 3 subfolders in the main project folder - rmdbook, mdbook,
> and the autogenerated _book from gitbook. The workflow, as I imagine, would
> be to do all editing in the rmd files, then similar to how you can
> devtools::document() for roxygenizing your documentation, you would
> render_book() which would automatically render all Rmd's to markdown in
> the mdbook folder. From there you could call something along the lines of
> create_book().
>
> This would also make it "easy" to do things like auto check for diff's
> between the md and Rmd versions and only re-render the rmd files that have
> changed, etc. Eventually, could likely hide the intermediate mdbook folder,
> but makes it much easier to troubleshoot and simplifies the build process.
>
> I started a repo lpgitbook (literate-programming gitbook) but realized I
> was unsure of some of the gitbook build processes (eg is the summary
> created automatically or does the user need to create that) so its not
> functional at all the moment, but hopefully I'll get some time in the
> future to work on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GitbookIO/gitbook/issues/307#issuecomment-78972665>.
>



-- 

Best Wishes
Steve Powell
_____________________________________________________________

Currently consultant to IFRC to develop an Evaluation Framework for Haiti<
http://goo.gl/1JW4O>

skype stevepowell99 | +387 61 215 997 | www.socialdatablog.com

**Comment by dpastoor** [comment]
I will see what I can come up with! I am swamped the next week or so but then should be able to take an initial crack at it.

**Comment by dpastoor** [comment]
and @maxheld83 I think I'd imagine more of a `publish_gh()` that would provide that kind of branch as a sort of 'read-only' branch only for directly pushing to gh to keep the confusion down. I'll definitely think on it, and some of it will just be getting people's feedback on their use-cases/workflow once it works in a minimum capacity

**Comment by aryamanarora** [comment]
Check out `bookdown`.
