### ISSUE TITLE
Bug: I always get "Parameter 'url' must be a string, not object"

### ISSUE THREAD

**Issue by simonech** [GitbookIO/gitbook#321]
With the latest version (0..5.3), every time I do anything, serve, build, I get the error
Parameter 'url' must be a string, not object

It was working last time I used it a few weeks ago

**Comment by sanand0** [comment]
This doesn't work as expected. I created a `SUMMARY.md` with a single external link:

    - [External link](http://www.google.com/)

This renders a link `<a target="_blank" href="http:/www.google.com/">`. Note the **single slash** in `http:/www.google.com`. This is treated as a **relative link to ./www.google.com/**, not an external link.

This is probably because we [normalize links as paths](https://github.com/GitbookIO/gitbook-parsers/blob/master/lib/summary.js#L36):

    return path.normalize(p).replace(/\\/g, '/').replace(/^\/+/, '');
                ^^^^^^^^^^^^

Perhaps we should check if it's an external link, and normalize it only if it's not?
