### ISSUE TITLE
Add option to ignore README.md

### ISSUE THREAD

**Issue by davefp** [GitbookIO/gitbook#392]
My book doesn't use README.md as the introduction. Instead, it's a guide to contributing, how to build the book, etc..

As such, I don't want it included in the summary at all. As far as I can tell this isn't possible. Adding the file to .bookignore causes the following error:

`ENOENT, stat '/Users/david/code/books/webhookbook/_book/index.html'`

My preferred solution would be an option entry in `book.json` called `ignoreReadme` or something similar that when set to true would simply let me skip adding the README to the summary.

**Comment by gbonanome** [comment]
+1 to the feature.

**Comment by petermichaux** [comment]
+1

**Comment by SamyPesse** [comment]
Since version 2.0.0, this is fixed by configuration:

```
{
  "structure": {
    "readme": "OTHER_README.md"
  }
}
```

**Comment by Abel-Torres** [comment]
Gitbook demands the README.md file. I don't want to use it. Why should the editor impose itself on my work?

**Comment by piranna** [comment]
It's not the only place where this happens, it was not easier to use
directly GitHub repos for plugins... According to the authors, this is done
to make it easier to use by people that know nothing about Node.js and npm,
but this way of thinking complicates too much to us advance users and
gitbook architecture and development itself. What a shame :-(

**Comment by SamyPesse** [comment]
@Abel-Torres You can use another file than `README.md` as introduction by modifying the `book.json`:

```
{
  "structure": {
    "readme": "OTHER_README.md"
  }
}
```

The editor should support it, but when opening the book it might try to always open the `README.md`. We are working on improving the editor to fix this kind of UX issues.

@piranna You can use GitHub repos for plugins now (starting with version `2.6.7`, and better support in `3.0.0`):

```js
{
    "plugins": ["test@git+https://github.com/You/myGitBookPlugin.git"]
}
```

**Comment by piranna** [comment]
> @piranna You can use GitHub repos for plugins now (starting with version 2.6.7, and better support in 3.0.0):
> 
> {
>     "plugins": ["test@git+https://github.com/You/myGitBookPlugin.git"]
> }

Ok, good to know, last time I test it was on previous versions (2.0.x or so). SInce now I'm using 2.6.7 I'm going to give it a try :-)

**Comment by SamyPesse** [comment]
@piranna If it's not working as expected, it will in version `3.0.0` (A few fixes have been implemented on this: support for SSH urls, etc).

**Comment by piranna** [comment]
> @piranna If it's not working as expected, it will in version 3.0.0 (A few fixes have been implemented on this: support for SSH urls, etc).

Yeah, there's A LOT of features and bug-fixes in 3.0.0 that I need for my thesis, but since the dateline to give a printed copy in secretary is the next friday 13th I don't think I would be able to move to it yet, specially due to plugins support... :-/ I'll try to give latest alpha version a try this weekend, but do you have an extimated date when 3.0.0 final will be released?

**Comment by SamyPesse** [comment]
@piranna What is the link to your book on GitBook.com ? (I can easily test it with GitBook v3)
What plugins are you using?

We still have a few bugs to fix before releasing, and we want to ensure compatibility with the max number of plugins.

**Comment by piranna** [comment]
> @piranna What is the link to your book on GitBook.com ? (I can easily test it with GitBook v3)

https://github.com/piranna/pfc It's a private repo, but I've give you access to it. I'll open it with a CreativeCommons licence when I present the thesis (not more than a months).


> What plugins are you using?

anchors, autocover, image-captions, indexes, mermaid and printlinks

Both autocover and mermaid use specific commits due to incompatibilites with newer versions, but they are correctly installed with `npm install`:

GitbookIO/plugin-autocover#452ba6c
JozoVilcek/gitbook-plugin-mermaid#c9b5c82


> We still have a few bugs to fix before releasing, and we want to ensure compatibility with the max number of plugins.

Seems [image captions](https://github.com/todvora/gitbook-plugin-image-captions/issues/8#issuecomment-217387215) is having some issues, don't know others...

**Comment by todvora** [comment]
@piranna, @SamyPesse: yes, image-captions is broken since ```3.0.0-pre.10``` due to missing ```summary.walk``` function. I don't see any replacement or alternative right now. The plugin works OK in ```3.0.0-pre.9```, if it helps to compile your thesis.

**Comment by cycomachead** [comment]
> I don't see any replacement or alternative right now. The plugin works OK in 3.0.0-pre.9, if it helps to compile your thesis.

Running into the same problems, and this is my current workaround.

**Comment by SamyPesse** [comment]
@todvora @cycomachead Happy to implement this PAI back in the new version (or implement a cleaner API), the API for plugins since version `3.0.0-pre.10` is correctly separated: https://github.com/GitbookIO/gitbook/blob/master/lib/api/encodeGlobal.js

@todvora What API signature to access the SUMMARY to you think is better? Something to get the whole summary as a tree ? Something equivalent to `walk` ?

**Comment by todvora** [comment]
@SamyPesse Thanks! I like the ```walk``` variant. Currently I need ordered summary, access to page.level, page.content (html or at least raw content) and page.ref to be able to build images registry with backlinks to figures on different pages. [Here](https://github.com/todvora/gitbook-plugin-image-captions/blob/82161381edbc1e7ab0d685f188930ae8a8800bb7/src/lib/ImageCaptions3.js#L28) is the ```pre.9``` implementation of image-captions plugin's ```walk``` callback.

**Comment by cycomachead** [comment]
I spent a few hours trying to read through the plugin's code as well as GitBook's. I think the `walk` method is pretty useful. I might end up using it for another plugin I'm messing with. (I think you could get by with simply accessing `book.summary`, but that's also deprecated.)
