### ISSUE TITLE
localize table of content

### ISSUE THREAD

**Issue by piranna** [GitbookIO/gitbook#504]
the table of content has its name hardcoded on the top in english, it should localize to the book language, or at least allow to override it.

**Comment by Ebizproduction** [comment]
Is there a way to create a plugin to override this ?

**Comment by AaronO** [comment]
@piranna @Ebizproduction In which output formats ?

Could you attach screenshots to clarify exactly what you're referring to ?

**Comment by Ebizproduction** [comment]
I think we are both referring to : gitbook/theme/templates/ebook/summary.html (line 3)
when compiling to epub or pdf.

`{% block title %}Table of Contents | {{ title }}{% endblock %}``

Table of Contents is hard-coded, and i'd like to render it as "Table des matières" or "Sommaire" in French.

**Comment by winniehell** [comment]
Yes, please give other languages a chance to use GitBook! :+1:
Actually, the problem seems to be located at [line 40](/GitbookIO/gitbook/blob/3a0f004/theme/templates/ebook/summary.html#L40). I could not find any documentation on how to overwrite templates. The [help](http://help.gitbook.io/book/themes.html) is not very helpful in that context. :disappointed:

**Comment by piranna** [comment]
Yes, I was talking about that line

**Comment by CoDEmanX** [comment]
I believe this issue can be closed, because it seems to be implemented:
https://github.com/GitbookIO/gitbook/pull/556/
