### ISSUE TITLE
Live reload hangs with Emacs

### ISSUE THREAD

**Issue by ludofischer** [GitbookIO/gitbook#520]
When editing a file `title.md`, Emacs creates a copy `.#title.md`, which disappers on save. When this happens, the live reload server sometimes hangs with the message 'ENOENT, no such file or directory'.

**Comment by ludovicofischer** [comment]
My previous comment is wrong. This is an issue with the gaze library used for file watching. The issue has been fixed in gaze 0.6 (https://github.com/shama/gaze/issues/58) but that same version does not build on node 0.12 and io.js (https://github.com/shama/gaze/issues/173). I’d wait for a new gaze version to switch?

**Comment by jeffbski** [comment]
+1

**Comment by jilen** [comment]
I met this bug, its really annoying is there any workaround ?

**Comment by mar9000** [comment]
+1 seems nobody is using emacs+gitboot
