### ISSUE TITLE
Any way to remove .html extension from URL?

### ISSUE THREAD

**Issue by rahul286** [GitbookIO/gitbook#537]
As an example:

For http://help.gitbook.io/book/errors.html

Can we generate it as http://help.gitbook.io/book/errors/index.html , which will give cleaner URLs like http://help.gitbook.io/book/errors/  ?

**Comment by josephkandi** [comment]
+1

**Comment by sashadt** [comment]
@SamyPesse This issue described here is still not resolved.  I was not able to find a way to convert `example.md` to `example/index.html` instead of currently generated `example.html`.  I saw a comment saying this feature might be coming soon, but I am not able to find the verion or sources with such functionality.
