### ISSUE TITLE
couldn't output chinese?

### ISSUE THREAD

**Issue by gantoday** [GitbookIO/gitbook#636]
use gitbook to generate a PDF,but couldn't output chinese in my md file.

how to fix it? please help me.

![image](https://cloud.githubusercontent.com/assets/7780154/6542031/b4eb0ec0-c526-11e4-9187-97bfef94b632.png)

**Comment by SamyPesse** [comment]
Can you give me a source file as an example or a link to download the source of your book.

**Comment by gantoday** [comment]
@SamyPesse https://github.com/laravel-china/docs thanks

**Comment by SamyPesse** [comment]
You are using `readme.md` instead of `README.md` and there is no `SUMMARY.md`. This book is not a valid GitBook, how did you build the pdf?

**Comment by gantoday** [comment]
@SamyPesse I download those md files in a directory ,and add my readme and summary file manually.

**Comment by gantoday** [comment]
@SamyPesse https://github.com/gantoday/docs 

this is my book's source file and pdf my build.

many thanks.

**Comment by SamyPesse** [comment]
This is working fine locally with the latest version of GitBook (in development), so it'll work fine on gitbook.com.

It's maybe not working on your computer because of the font installed or the version of ebook-convert.

![screen shot 2015-03-08 at 22 46 39](https://cloud.githubusercontent.com/assets/845425/6547854/2aeb5bde-c5e5-11e4-9557-dd3aa69297cf.png)
![screen shot 2015-03-08 at 22 46 33](https://cloud.githubusercontent.com/assets/845425/6547855/2b141fd8-c5e5-11e4-9603-c8286129357f.png)

**Comment by johnsonjie** [comment]
hello  have u  fixed  this problem？I've met the same thing

**Comment by johnsonjie** [comment]
@gantoday

**Comment by gantoday** [comment]
@johnsonjie 我已经忘记了
