### ISSUE TITLE
Bengali fonts

### ISSUE THREAD

**Issue by uroybd** [GitbookIO/gitbook#643]
It's amazing that you have solved major Bengali font rendering problem in generated pdf ebook. But the fonts are not good. Normal one is readable but in the block of codes it's horrible. If you replace both of them with SolaimanLipi(which is standard unicode font for Bengali) or the one you used in normal text, use it for every Bengali text.

Thanks
![bug](https://cloud.githubusercontent.com/assets/4207230/6633972/5d6a94aa-c97b-11e4-96e4-520dfe6b00d2.png)

**Comment by nasirkhan** [comment]
Can you please provide the URL of your book, if it is not published yet then please make an arrangemnt so that i can view and compile by my own. 

For your information i would like to inform you that the 'SolaimanLipi' font has lot of issues and there are other standard Bengali Unicode fonts available.
