### ISSUE TITLE
render error when content has {% or %}

### ISSUE THREAD

**Issue by looly** [GitbookIO/gitbook#685]
Template render error: unknown block tag: end (In file '300/312.md', Line 79, Column 6)

**Comment by looly** [comment]
When I use Gitbook2.0, Gitbook2.0 template is conflict with my content!

**Comment by AaronO** [comment]
@looly Sorry about that, in the settings you can switch back to `1.x.x`. Do you have a link to your book (or source on GitHub) ? So we can see what's causing the issue.

@SamyPesse Maybe if templating fails like this, we should fallback to the plain file (be less strict about templating, since it can break from false positives like here and templating not working is less frustrating that the build failing, this could be enabled a `non-strict` flag that we could/should enable on `GitBook.com` ?)

**Comment by AaronO** [comment]
@looly Ok, after seeing your tweet, it seems like we maybe aren't escaping code blocks that are indented .

If you use

    ```
    YOUR_STUFF
    ```

instead of 

```
    YOUR_STUFF
```

That will probably work (as a quick fix).

I'll see about fixing this in https://github.com/GitbookIO/gitbook-markdown

**Comment by looly** [comment]
It`s work when I switch back to 1.x，my book content is [https://github.com/looly/python-basic/blob/master/300/312.md](https://github.com/looly/python-basic/blob/master/300/312.md)

Thank you for reply

**Comment by Stanton** [comment]
I think I'm having the same issue, switching to ``` didn't resolve the issue for me: 

eg: this snippet wrapped in the backticks

```
{{ html.wtf() }}
```
fails the build with the following error:
```
Downloading source
Extracting source
Current version is 2.0.1
Tweaking book.json
Installing plugins
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: 1 plugins to install 
info: No version specified, resolve plugin autocover 
info: install plugin autocover from npm (gitbook-plugin-autocover) with version 1.2.1 
info: >> plugin autocover installed with success 

Done, without error
Building Site, will upload
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 

Template render error: Unable to call `html["wtf"]`, which is undefined or falsey```
