### ISSUE TITLE
Custom Menu (expand/collapse)

### ISSUE THREAD

**Issue by edsiper** [GitbookIO/gitbook#717]
Is there any configuration flag or plugin that allow to have a collapsed menu when generating the HTML content ?

**Comment by brenoc** [comment]
:+1: That's a nice feature

**Comment by 13abylon** [comment]
I would also like to see that feature :+1:

**Comment by 13abylon** [comment]
I've found a great plugin for the toggle:
https://github.com/poojan/gitbook-plugin-toggle-chapters

I think this issue can be closed, if this was the plugin you have look for :)

**Comment by brenoc** [comment]
@13abylon @poojan that's great! Thanks!

**Comment by jerger** [comment]
Hi,

we just published a similar plugin but with dedicated collapse / expand of chapters instead of  toggle. You can find the plugin at https://www.npmjs.com/package/gitbook-plugin-expandable-chapters or at https://github.com/DomainDrivenArchitecture/gitbook-plugin-expandable-chapters

Much fun with using it :-)

**Comment by teone** [comment]
In case someone needs it this plugin https://www.npmjs.com/package/gitbook-plugin-smart-nav-collapse will collapse also items that don't have a page associated with them
