### ISSUE TITLE
Google Custom Search Support

### ISSUE THREAD

**Issue by rahul286** [GitbookIO/gitbook#748]
Is it possible to replace Gitbook search with Google Custom Search?

I like Gitbook but I feel for large books, Google Custom Search might be better in our case. 
We have our documentation scattered over multiple gitbooks. So it's more about searching across "books".

Also, if gitbook builtin search disabled, will it speed up gitbook generation or page load-time? 

Gitbook is already fast. Just want to know delay search related part adds.

**Comment by AaronO** [comment]
@rahul286 What we'll likely do short/mid-term is index all books in `elasticsearch` (or similar solution), this would have the benefit of providing cross book search and we need to use something that we can ship to enterprise customers.

Search would then be faster and it would be possible to query across books, this would require a little bit of engineering on our side to keep everything in sync, but I think it would be the best solution.

Disabling search will speedup book generation and load time (load time less because it's only loaded when needed), we are looking into putting a CDN in front of GitBook books which will provide a great speed improvement.
