### ISSUE TITLE
pre / html block breaks on '<=' 

### ISSUE THREAD

**Issue by dothebart** [GitbookIO/gitbook#842]
this section from the markdown: 

    <div id="geoIndexCreateForArrayAttribute_long" onclick="" style="Display: none;">
    <pre>
    arangosh> for (i = -90;  i <= 90;  i += 10) {
    ........>     for (j = -180; j <= 180; j += 10) {
    ........>         db.geo.save({ name : "Name/" + i + "/" + j, loc: [ i, j ] });
    ........>     }
    ........> }	
    </pre>
    </div>

becomes:

    arangosh&gt; for (i = -90;  i <= 90;="" i="" +="10)" {="" ........="">     for (j = -180; j <= 180;="" j="" +="10)"     {="" ........="">         db.geo.save({ name : &quot;Name/&quot; + i + &quot;/&quot; + j, loc: [ i, j ] });
    ........&gt;     }
    ........&gt; }    
    arangosh&gt; db.geo.count();
until after <=90 everything is fine - then things go bad.

**Comment by AaronO** [comment]
@dothebart Do you have a link to the full source ?

**Comment by dothebart** [comment]
oh, it already posted - was still creating the gist ;-) https://gist.github.com/dothebart/fdf586deab7c4d6a66be

**Comment by SamyPesse** [comment]
This is failing (in the editor) because `<=` is considered as a tag.

In the editor I'm getting the error:

<img width="403" alt="screen shot 2015-09-06 at 21 21 36" src="https://cloud.githubusercontent.com/assets/845425/9706150/48d633bc-54dd-11e5-84b2-41bb3aa186c0.png">


But it looks like it has been fixed by https://github.com/GitbookIO/kramed/pull/24 since the master is outputting:

<img width="790" alt="screen shot 2015-09-06 at 21 20 47" src="https://cloud.githubusercontent.com/assets/845425/9706148/399de82c-54dd-11e5-9dbe-6871b49c985f.png">

**Comment by SamyPesse** [comment]
I just fixed it in the editor, it will be in the next release.
