### ISSUE TITLE
Support Bitbucket

### ISSUE THREAD

**Issue by pedromorgan** [GitbookIO/gitbook#889]
Bitcbucket support would be fantastic

**Comment by quangbahoa** [comment]
+1

**Comment by juaalta** [comment]
+1

**Comment by AaronO** [comment]
The problem with BitBucket is that it's API is subpar, it's nowhere near as complete as GitHub's.

I don't think the API allows you to interact with the repository's contents itself, via a "contents" API or even a lower level "git" API.

So we could easily get webhooks working, but I don't think we could get the web editor working with BitBucket (until they improve/expand their API).

One way you can use BitBucket is via the desktop editor. But we can't support something officially if there's no way for us to make it work well for the user, bad partial support of BitBucket would be much more confusing that no support IMHO.

**Comment by pedromorgan** [comment]
Asking atlassian what position is..

https://bitbucket.org/site/master/issues/11787/does-the-git-api-support-content

**Comment by xtrasmal** [comment]
@pedromorgan I've got my books in Bitbucket. 

- First I create a repo on bitbucket. 
- then I clone it somewhere on my local disk
- then I select import from the gitbook editor. 
- and on sync it asks me for the password, which I then save and 
- syncing time

**Comment by mudongliang** [comment]
:+1:

**Comment by gitovers** [comment]
@xtrasmal thanks

**Comment by KlausUnger-SoftwareCraftsmen** [comment]
+1

**Comment by renyouguo** [comment]
+1

**Comment by rupakanto** [comment]
+1

**Comment by xsuoownit** [comment]
@xtrasmal Where does the gitbook published to? How can I configure that?

**Comment by xtrasmal** [comment]
@xsuoownit: On OSX it publishes to ```~/GitBook/Library```
You can change this by going to ```File -> Change Library Path...```

**Comment by systemsoverload** [comment]
Bitbucket dev here (replying on unofficial terms atm), new to Gitbook and haven't touched the editor much yet. What kind of integration points do you need on the Bitbucket side of the equation? Pardons in advance if that's a dull question.

**Comment by AaronO** [comment]
Hi @systemsoverload,

It would actually be quite easy to implement now on a technical level, as long as it makes product-sense. Because we've changed how our git sync works.

The problem was that BitBucket didn't have very good APIs to access any of the repo's actual git data.

### Before

The web editor would connect directly to GitHub's API and leverage its git APIs to load/edit content (read trees/blobs, create blobs/commits/...). (Using the user's GitHub oAuth'd credentials).

### Now

The web editor connects to our homemade git server, which implements all of GitHub's git-related API methods (and a few extras). New commits made via the API (or pushed to our server) trigger a "mirroring" system which syncs the data via the git-protocol to GitHub.

So it could in theory push to any git repo so long as we have the correct auth. (We use GitHub's new "Integrations APIs" to get project/org level auth tokens).

**Comment by AaronO** [comment]
@systemsoverload To answer your original question, in terms of integration points the following are required:
- A nice reliable way to obtain user-independant project/repo level auth tokens (So we can sync regardless of who edited on our end)
- Be able to use that token to `git pull/push` to that repo over `https`

So on a technical level it's very doable, it's more of a product/roadmap/prioritization question (since we're a small team)

**Comment by systemsoverload** [comment]
@AaronO Thanks for getting back to me. I'll take this to PM next week and see what we can do, but I actually don't think there is any significant blockers on our end at first blush.

**Comment by r3bo0t** [comment]
@systemsoverload any update on the same? Were you guys able to put this on your priority list?
cc: @AaronO

**Comment by ggomersall** [comment]
@systemoverload
What was the outcome with potential integration of bitbucket with gitbook ?
cc:@AaronO

**Comment by sjhansen3** [comment]
+1

**Comment by micdah** [comment]
👍

**Comment by benje** [comment]
👍

**Comment by ian-dick** [comment]
@AaronO 
Another Bitbucket Cloud dev here. I'll try addressing the requirements you outlined in that last comment, specifically the need to be able to push/pull repositories over HTTPS.

There is a way to do this with out current architecture. You would [create an app](https://developer.atlassian.com/cloud/bitbucket/getting-started/), and once you have the app installed into an account in Bitbucket, you can exchange a JWT token for an oauth token for the acccount via the [Bitbucket API](https://developer.atlassian.com/cloud/bitbucket/oauth-2/) - check out grant type 5. Then you can push/pull the repository over https using this token.

In the future, you won’t need to implement JWT handling at all, you will be able to create an app and get an oauth consumer associated with your app at initialization time, and you’ll be able to create a token using this consumer that you can use to push/pull repositories in accounts where your app is installed. This latter work is a few months away, I don’t have a firm release date for it, but it would be unfortunate if you went ahead and spent a bunch of time implementing JWT-handling and then realized later that you didn’t need to.

I guess what you end up doing will depend on how soon you want to ship Bitbucket support. Hope this is helpful.

**Comment by Vadorequest** [comment]
I'd be very much interested by a Bitbucket integration, most of our private work is on bitbucket, only public repo are on github.

**Comment by MatinF** [comment]
Any updates on an ETA for this integration? Thanks
