### ISSUE TITLE
PDF.css options

### ISSUE THREAD

**Issue by xtrasmal** [GitbookIO/gitbook#942]
Hello there, 

Can somebody tell me if there is a list of things I am able to style?
Is there a boilerplate CSS file which I can copy over per book?

**Comment by TomasKulhanek** [comment]
It seems that pdf.css options are not taken into account when seeing PDF output. The generated PDF using latest gitbook version 2.4.3 contains duplicated chapter headings in a page. While this duplicated heading should be prevented by the default theme/assets/ebook/pdf.css:
<code> .page .book-chapter{display:none} </code>
It is not. 
The only option which works for me is 
<code>p,
blockquote,
ul,
ol,
dl,
table,
pre {
  text-align: justify;
} 
</code>
which stretches the lines in a paragraph so that each line has equal width.
