### ISSUE TITLE
Use of </br> tag in GitBook

### ISSUE THREAD

**Issue by FMEEvangelist** [GitbookIO/gitbook#947]
Am I able to use the HTML tag \</br> in GitBook? It doesn't seem to get rendered. Instead I get...

1) Start FME Workbench\</br> Start FME Workbench by....

**Comment by FMEEvangelist** [comment]
So if I use:

1) Start Workbench\</br>
Start Workbench by clicking...

...then it doesn't render. But it does render properly if I use this:

1) Start Workbench
\<br>Start Workbench by clicking...

**Comment by SamyPesse** [comment]
Ok, I've run some test and I can reproduce the issue:

```md
# Hello


test<br>hello

test<br/>hello

test</br>hello

```

output:

![screen shot 2015-09-25 at 20 57 59](https://cloud.githubusercontent.com/assets/845425/10109610/31ab95b6-63c8-11e5-9661-865a1445e90f.png)

I think it's probably related to how [kramed](https://github.com/GitbookIO/kramed) handle html tasg.

@AaronO can you take a look?

**Comment by AaronO** [comment]
@FMEEvangelist Most browsers will render `</br>` (because do their best to render most documents, even broken ones).

But `</br>` is not standard or valid. HTML supports `<br>` and the older XHTML standard supported `<br/>`. (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br)

So I would recommend using either `<br>` or `<br/>`, which we should both support perfectly :)

Out of curiosity is there a specific reason why you were using `</br>` instead of `<br>` or `<br/>` ?
