### ISSUE TITLE
Links in theme Sepia are not distinguishable from text

### ISSUE THREAD

**Issue by Aybee** [GitbookIO/gitbook#949]
# Theme Night

![installing_contao_manual_for_contao_3 5_-_2015-09-25_23 49 45](https://cloud.githubusercontent.com/assets/1143013/10113154/eb89f004-63e1-11e5-9515-8fa74b9a6807.png)
# Theme White

![installing_contao_manual_for_contao_3 5_-_2015-09-25_23 48 25](https://cloud.githubusercontent.com/assets/1143013/10113140/b261b398-63e1-11e5-9777-35c68fd78b1f.png)
# Theme Sepia

![installing_contao_manual_for_contao_3 5_-_2015-09-25_23 50 17](https://cloud.githubusercontent.com/assets/1143013/10113162/fb8b41f6-63e1-11e5-9e7c-68e5990be2b7.png)
Maybe you should make them **underline**
![installing_contao_manual_for_contao_3 5_-_2015-09-25_23 55 16](https://cloud.githubusercontent.com/assets/1143013/10113168/09738080-63e2-11e5-89ed-4e52f0fea852.png)

Found on this page https://docs.contao.org/books/manual/3.5/en/01-installation/installing-contao.html#importing-a-template

**Comment by schlomo** [comment]
I solved this problem with a [custom CSS](https://help.gitbook.com/content/how-can-i-include-css.html) `styles/website.css` file with the following content:

```css
.book.color-theme-1 .book-body .page-wrapper .page-inner section.normal a {
    color: initial;
}
```

I changed `color: inherit` to `color: initial` and the links turned black which is fine for sepia. I wanted to stay with a color decoration so that links in underlined text would still be visible as links.
