### ISSUE TITLE
EPUB max font size too small

### ISSUE THREAD

**Issue by eduedix** [GitbookIO/gitbook#989]
I am reading a book prepared with gitbook on my ipad mini 2 using iBooks app. I contacted the author of the book because the max font size was still small to read. The author suggested contacting gitbook for that issue.
Following is the link to the issue of the book I am reading:
https://github.com/MostlyAdequate/mostly-adequate-guide/issues/175

**Comment by SamyPesse** [comment]
What ebook reader are you using ?

**Comment by eduedix** [comment]
iBooks app on ipad.

**Comment by smussell** [comment]
I see the same issue with both the book mentioned above and https://www.gitbook.com/book/gitbookio/javascript/details. I'm using the iPad iBooks app on iOS 9.1. I can't get the font size to change at all and the default font seems a little to small for me. Thanks.

**Comment by JayPanoz** [comment]
Don't know if you fixed that yet (issue still open) but you may want to get rid of 

```
.page {
   -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
```
in stylesheet.css.

It actually disable font-size setting in iBooks iOS.

And since I'm parsing your CSS right now, here are other things which may deteriorate UX in some other reading systems: 

- `color: #333;` → please don't declare gray–black for text as some apps won't invert it in night modes. As a result, gray/black text on dark background.
-  `position: relative;` → please note iBooks devs are overriding this specially for calibre stylesheet as it creates rendering problems. From iBooks' default CSS tmpl: `.calibre > div, .calibre1 > div {position: static !important;}`
- `currentColor` → I wouldn't rely on that given its support % in ePub reading systems.
- `box-sizing: border-box;` → same as above.

And that's it.

**Comment by BrianHicks** [comment]
I'm hearing this from a reader as well. Why does gitbook disable resizing?

**Comment by nateberkopec** [comment]
Just heard this from a reader as well. Not sure why that CSS rule exists.
